/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TAccountMotRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMot extends TableImpl<TAccountMotRecord> {

    private static final long serialVersionUID = -495366492;

    /**
     * The reference instance of <code>datasync.t_account_mot</code>
     */
    public static final TAccountMot T_ACCOUNT_MOT = new TAccountMot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAccountMotRecord> getRecordType() {
        return TAccountMotRecord.class;
    }

    /**
     * The column <code>datasync.t_account_mot.FUND_ACCOUNT</code>.
     */
    public final TableField<TAccountMotRecord, String> FUND_ACCOUNT = createField("FUND_ACCOUNT", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>datasync.t_account_mot.MOT_MARK</code>. 用户标签
     */
    public final TableField<TAccountMotRecord, String> MOT_MARK = createField("MOT_MARK", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "用户标签");

    /**
     * The column <code>datasync.t_account_mot.MOT_LEVEL</code>. MOT等级
     */
    public final TableField<TAccountMotRecord, BigDecimal> MOT_LEVEL = createField("MOT_LEVEL", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "MOT等级");

    /**
     * The column <code>datasync.t_account_mot.MOT_EXTEND</code>. MOT详情,JSON格式
     */
    public final TableField<TAccountMotRecord, String> MOT_EXTEND = createField("MOT_EXTEND", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "MOT详情,JSON格式");

    /**
     * The column <code>datasync.t_account_mot.UPDATE_TIME</code>. 更新时间
     */
    public final TableField<TAccountMotRecord, Timestamp> UPDATE_TIME = createField("UPDATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>datasync.t_account_mot</code> table reference
     */
    public TAccountMot() {
        this("t_account_mot", null);
    }

    /**
     * Create an aliased <code>datasync.t_account_mot</code> table reference
     */
    public TAccountMot(String alias) {
        this(alias, T_ACCOUNT_MOT);
    }

    private TAccountMot(String alias, Table<TAccountMotRecord> aliased) {
        this(alias, aliased, null);
    }

    private TAccountMot(String alias, Table<TAccountMotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAccountMotRecord> getPrimaryKey() {
        return Keys.KEY_T_ACCOUNT_MOT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAccountMotRecord>> getKeys() {
        return Arrays.<UniqueKey<TAccountMotRecord>>asList(Keys.KEY_T_ACCOUNT_MOT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMot as(String alias) {
        return new TAccountMot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TAccountMot rename(String name) {
        return new TAccountMot(name, null);
    }
}
