/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TAccountMarkProdInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMarkProdInfo extends TableImpl<TAccountMarkProdInfoRecord> {

    private static final long serialVersionUID = -609130947;

    /**
     * The reference instance of <code>datasync.t_account_mark_prod_info</code>
     */
    public static final TAccountMarkProdInfo T_ACCOUNT_MARK_PROD_INFO = new TAccountMarkProdInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAccountMarkProdInfoRecord> getRecordType() {
        return TAccountMarkProdInfoRecord.class;
    }

    /**
     * The column <code>datasync.t_account_mark_prod_info.PROD_TYPE</code>. 标签类别
     */
    public final TableField<TAccountMarkProdInfoRecord, UInteger> PROD_TYPE = createField("PROD_TYPE", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "标签类别");

    /**
     * The column <code>datasync.t_account_mark_prod_info.PROD_CODE</code>. 产品代码
     */
    public final TableField<TAccountMarkProdInfoRecord, String> PROD_CODE = createField("PROD_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "产品代码");

    /**
     * The column <code>datasync.t_account_mark_prod_info.UPDATE_TIME</code>. 更新时间
     */
    public final TableField<TAccountMarkProdInfoRecord, Timestamp> UPDATE_TIME = createField("UPDATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * The column <code>datasync.t_account_mark_prod_info.PROD_CATEGORY</code>. 产品类别
     */
    public final TableField<TAccountMarkProdInfoRecord, String> PROD_CATEGORY = createField("PROD_CATEGORY", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "产品类别");

    /**
     * Create a <code>datasync.t_account_mark_prod_info</code> table reference
     */
    public TAccountMarkProdInfo() {
        this("t_account_mark_prod_info", null);
    }

    /**
     * Create an aliased <code>datasync.t_account_mark_prod_info</code> table reference
     */
    public TAccountMarkProdInfo(String alias) {
        this(alias, T_ACCOUNT_MARK_PROD_INFO);
    }

    private TAccountMarkProdInfo(String alias, Table<TAccountMarkProdInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TAccountMarkProdInfo(String alias, Table<TAccountMarkProdInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAccountMarkProdInfoRecord> getPrimaryKey() {
        return Keys.KEY_T_ACCOUNT_MARK_PROD_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAccountMarkProdInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TAccountMarkProdInfoRecord>>asList(Keys.KEY_T_ACCOUNT_MARK_PROD_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkProdInfo as(String alias) {
        return new TAccountMarkProdInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TAccountMarkProdInfo rename(String name) {
        return new TAccountMarkProdInfo(name, null);
    }
}
