/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TAccountMarkRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMark extends TableImpl<TAccountMarkRecord> {

    private static final long serialVersionUID = -646980349;

    /**
     * The reference instance of <code>datasync.t_account_mark</code>
     */
    public static final TAccountMark T_ACCOUNT_MARK = new TAccountMark();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAccountMarkRecord> getRecordType() {
        return TAccountMarkRecord.class;
    }

    /**
     * The column <code>datasync.t_account_mark.FUND_ACCOUNT</code>.
     */
    public final TableField<TAccountMarkRecord, String> FUND_ACCOUNT = createField("FUND_ACCOUNT", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>datasync.t_account_mark.MARK_TYPE</code>. 标签类型
     */
    public final TableField<TAccountMarkRecord, UInteger> MARK_TYPE = createField("MARK_TYPE", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "标签类型");

    /**
     * The column <code>datasync.t_account_mark.MARK_VALUE</code>. 用户标签
     */
    public final TableField<TAccountMarkRecord, UInteger> MARK_VALUE = createField("MARK_VALUE", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "用户标签");

    /**
     * The column <code>datasync.t_account_mark.UPDATE_TIME</code>. 更新时间
     */
    public final TableField<TAccountMarkRecord, Timestamp> UPDATE_TIME = createField("UPDATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>datasync.t_account_mark</code> table reference
     */
    public TAccountMark() {
        this("t_account_mark", null);
    }

    /**
     * Create an aliased <code>datasync.t_account_mark</code> table reference
     */
    public TAccountMark(String alias) {
        this(alias, T_ACCOUNT_MARK);
    }

    private TAccountMark(String alias, Table<TAccountMarkRecord> aliased) {
        this(alias, aliased, null);
    }

    private TAccountMark(String alias, Table<TAccountMarkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAccountMarkRecord> getPrimaryKey() {
        return Keys.KEY_T_ACCOUNT_MARK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAccountMarkRecord>> getKeys() {
        return Arrays.<UniqueKey<TAccountMarkRecord>>asList(Keys.KEY_T_ACCOUNT_MARK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMark as(String alias) {
        return new TAccountMark(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TAccountMark rename(String name) {
        return new TAccountMark(name, null);
    }
}
