/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TDictLvl2Record;


/**
 * 二级数据字典
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDictLvl2 extends TableImpl<TDictLvl2Record> {

    private static final long serialVersionUID = -100162926;

    /**
     * The reference instance of <code>datasync.t_dict_lvl2</code>
     */
    public static final TDictLvl2 T_DICT_LVL2 = new TDictLvl2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDictLvl2Record> getRecordType() {
        return TDictLvl2Record.class;
    }

    /**
     * The column <code>datasync.t_dict_lvl2.dict_item</code>. 字典项
     */
    public final TableField<TDictLvl2Record, String> DICT_ITEM = createField("dict_item", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "字典项");

    /**
     * The column <code>datasync.t_dict_lvl2.dict_key</code>. 字典项键名
     */
    public final TableField<TDictLvl2Record, String> DICT_KEY = createField("dict_key", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "字典项键名");

    /**
     * The column <code>datasync.t_dict_lvl2.dict_value</code>. 字典项键值
     */
    public final TableField<TDictLvl2Record, String> DICT_VALUE = createField("dict_value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "字典项键值");

    /**
     * The column <code>datasync.t_dict_lvl2.update_time</code>. 更新时间
     */
    public final TableField<TDictLvl2Record, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * The column <code>datasync.t_dict_lvl2.create_time</code>. 创建时间
     */
    public final TableField<TDictLvl2Record, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * Create a <code>datasync.t_dict_lvl2</code> table reference
     */
    public TDictLvl2() {
        this("t_dict_lvl2", null);
    }

    /**
     * Create an aliased <code>datasync.t_dict_lvl2</code> table reference
     */
    public TDictLvl2(String alias) {
        this(alias, T_DICT_LVL2);
    }

    private TDictLvl2(String alias, Table<TDictLvl2Record> aliased) {
        this(alias, aliased, null);
    }

    private TDictLvl2(String alias, Table<TDictLvl2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "二级数据字典");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDictLvl2Record> getPrimaryKey() {
        return Keys.KEY_T_DICT_LVL2_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDictLvl2Record>> getKeys() {
        return Arrays.<UniqueKey<TDictLvl2Record>>asList(Keys.KEY_T_DICT_LVL2_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2 as(String alias) {
        return new TDictLvl2(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDictLvl2 rename(String name) {
        return new TDictLvl2(name, null);
    }
}
