/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TDictLvl2DescRecord;


/**
 * 二级数据字典描述
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDictLvl2Desc extends TableImpl<TDictLvl2DescRecord> {

    private static final long serialVersionUID = 62466985;

    /**
     * The reference instance of <code>datasync.t_dict_lvl2_desc</code>
     */
    public static final TDictLvl2Desc T_DICT_LVL2_DESC = new TDictLvl2Desc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDictLvl2DescRecord> getRecordType() {
        return TDictLvl2DescRecord.class;
    }

    /**
     * The column <code>datasync.t_dict_lvl2_desc.dict_item</code>. 字典项
     */
    public final TableField<TDictLvl2DescRecord, String> DICT_ITEM = createField("dict_item", org.jooq.impl.SQLDataType.CHAR.length(64).nullable(false), this, "字典项");

    /**
     * The column <code>datasync.t_dict_lvl2_desc.dict_desc</code>. 字典项描述
     */
    public final TableField<TDictLvl2DescRecord, String> DICT_DESC = createField("dict_desc", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "字典项描述");

    /**
     * Create a <code>datasync.t_dict_lvl2_desc</code> table reference
     */
    public TDictLvl2Desc() {
        this("t_dict_lvl2_desc", null);
    }

    /**
     * Create an aliased <code>datasync.t_dict_lvl2_desc</code> table reference
     */
    public TDictLvl2Desc(String alias) {
        this(alias, T_DICT_LVL2_DESC);
    }

    private TDictLvl2Desc(String alias, Table<TDictLvl2DescRecord> aliased) {
        this(alias, aliased, null);
    }

    private TDictLvl2Desc(String alias, Table<TDictLvl2DescRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "二级数据字典描述");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDictLvl2DescRecord> getPrimaryKey() {
        return Keys.KEY_T_DICT_LVL2_DESC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDictLvl2DescRecord>> getKeys() {
        return Arrays.<UniqueKey<TDictLvl2DescRecord>>asList(Keys.KEY_T_DICT_LVL2_DESC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Desc as(String alias) {
        return new TDictLvl2Desc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDictLvl2Desc rename(String name) {
        return new TDictLvl2Desc(name, null);
    }
}
