/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TIndexSignalRecord;


/**
 * 指数信号信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndexSignal extends TableImpl<TIndexSignalRecord> {

    private static final long serialVersionUID = 142142868;

    /**
     * The reference instance of <code>datasync.t_index_signal</code>
     */
    public static final TIndexSignal T_INDEX_SIGNAL = new TIndexSignal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TIndexSignalRecord> getRecordType() {
        return TIndexSignalRecord.class;
    }

    /**
     * The column <code>datasync.t_index_signal.release_time</code>. 发布时间
     */
    public final TableField<TIndexSignalRecord, Timestamp> RELEASE_TIME = createField("release_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "发布时间");

    /**
     * The column <code>datasync.t_index_signal.trade_date</code>. 交易日期
     */
    public final TableField<TIndexSignalRecord, Date> TRADE_DATE = createField("trade_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "交易日期");

    /**
     * The column <code>datasync.t_index_signal.signal</code>. 信号
     */
    public final TableField<TIndexSignalRecord, String> SIGNAL = createField("signal", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "信号");

    /**
     * The column <code>datasync.t_index_signal.signal_type</code>. 信号类别（1：变盘信号）
     */
    public final TableField<TIndexSignalRecord, Short> SIGNAL_TYPE = createField("signal_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "信号类别（1：变盘信号）");

    /**
     * The column <code>datasync.t_index_signal.comment</code>. 点评
     */
    public final TableField<TIndexSignalRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB, this, "点评");

    /**
     * The column <code>datasync.t_index_signal.remark</code>. 备注
     */
    public final TableField<TIndexSignalRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "备注");

    /**
     * Create a <code>datasync.t_index_signal</code> table reference
     */
    public TIndexSignal() {
        this("t_index_signal", null);
    }

    /**
     * Create an aliased <code>datasync.t_index_signal</code> table reference
     */
    public TIndexSignal(String alias) {
        this(alias, T_INDEX_SIGNAL);
    }

    private TIndexSignal(String alias, Table<TIndexSignalRecord> aliased) {
        this(alias, aliased, null);
    }

    private TIndexSignal(String alias, Table<TIndexSignalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "指数信号信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TIndexSignalRecord> getPrimaryKey() {
        return Keys.KEY_T_INDEX_SIGNAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TIndexSignalRecord>> getKeys() {
        return Arrays.<UniqueKey<TIndexSignalRecord>>asList(Keys.KEY_T_INDEX_SIGNAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignal as(String alias) {
        return new TIndexSignal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TIndexSignal rename(String name) {
        return new TIndexSignal(name, null);
    }
}
