/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TIndexHistperfRecord;


/**
 * 历史预警后大盘指数表现信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndexHistperf extends TableImpl<TIndexHistperfRecord> {

    private static final long serialVersionUID = 291444933;

    /**
     * The reference instance of <code>datasync.t_index_histperf</code>
     */
    public static final TIndexHistperf T_INDEX_HISTPERF = new TIndexHistperf();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TIndexHistperfRecord> getRecordType() {
        return TIndexHistperfRecord.class;
    }

    /**
     * The column <code>datasync.t_index_histperf.release_time</code>. 发布时间
     */
    public final TableField<TIndexHistperfRecord, Timestamp> RELEASE_TIME = createField("release_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "发布时间");

    /**
     * The column <code>datasync.t_index_histperf.trade_date</code>. 交易日期
     */
    public final TableField<TIndexHistperfRecord, Date> TRADE_DATE = createField("trade_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "交易日期");

    /**
     * The column <code>datasync.t_index_histperf.index_code</code>. 指数类型代码（1-上证， 2-沪深300， 3-中证500， 4-深证）
     */
    public final TableField<TIndexHistperfRecord, String> INDEX_CODE = createField("index_code", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "指数类型代码（1-上证， 2-沪深300， 3-中证500， 4-深证）");

    /**
     * The column <code>datasync.t_index_histperf.index_name</code>. 指数名称（上证，深证，等）
     */
    public final TableField<TIndexHistperfRecord, String> INDEX_NAME = createField("index_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "指数名称（上证，深证，等）");

    /**
     * The column <code>datasync.t_index_histperf.close_price_before</code>. 当日股票收盘价
     */
    public final TableField<TIndexHistperfRecord, String> CLOSE_PRICE_BEFORE = createField("close_price_before", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "当日股票收盘价");

    /**
     * The column <code>datasync.t_index_histperf.close_price_after</code>. 30日后指数收盘价
     */
    public final TableField<TIndexHistperfRecord, String> CLOSE_PRICE_AFTER = createField("close_price_after", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "30日后指数收盘价");

    /**
     * The column <code>datasync.t_index_histperf.net_ratio</code>. 涨跌额
     */
    public final TableField<TIndexHistperfRecord, String> NET_RATIO = createField("net_ratio", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "涨跌额");

    /**
     * The column <code>datasync.t_index_histperf.ratio</code>. 涨跌幅
     */
    public final TableField<TIndexHistperfRecord, String> RATIO = createField("ratio", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "涨跌幅");

    /**
     * The column <code>datasync.t_index_histperf.remark</code>. 备注
     */
    public final TableField<TIndexHistperfRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "备注");

    /**
     * Create a <code>datasync.t_index_histperf</code> table reference
     */
    public TIndexHistperf() {
        this("t_index_histperf", null);
    }

    /**
     * Create an aliased <code>datasync.t_index_histperf</code> table reference
     */
    public TIndexHistperf(String alias) {
        this(alias, T_INDEX_HISTPERF);
    }

    private TIndexHistperf(String alias, Table<TIndexHistperfRecord> aliased) {
        this(alias, aliased, null);
    }

    private TIndexHistperf(String alias, Table<TIndexHistperfRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "历史预警后大盘指数表现信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TIndexHistperfRecord> getPrimaryKey() {
        return Keys.KEY_T_INDEX_HISTPERF_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TIndexHistperfRecord>> getKeys() {
        return Arrays.<UniqueKey<TIndexHistperfRecord>>asList(Keys.KEY_T_INDEX_HISTPERF_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperf as(String alias) {
        return new TIndexHistperf(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TIndexHistperf rename(String name) {
        return new TIndexHistperf(name, null);
    }
}
