/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TProdInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProdInfo extends TableImpl<TProdInfoRecord> {

    private static final long serialVersionUID = 1308430898;

    /**
     * The reference instance of <code>datasync.t_prod_info</code>
     */
    public static final TProdInfo T_PROD_INFO = new TProdInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProdInfoRecord> getRecordType() {
        return TProdInfoRecord.class;
    }

    /**
     * The column <code>datasync.t_prod_info.PROD_CODE</code>. 产品代码
     */
    public final TableField<TProdInfoRecord, String> PROD_CODE = createField("PROD_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "产品代码");

    /**
     * The column <code>datasync.t_prod_info.UPDATE_TIME</code>. 更新时间
     */
    public final TableField<TProdInfoRecord, Timestamp> UPDATE_TIME = createField("UPDATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>datasync.t_prod_info</code> table reference
     */
    public TProdInfo() {
        this("t_prod_info", null);
    }

    /**
     * Create an aliased <code>datasync.t_prod_info</code> table reference
     */
    public TProdInfo(String alias) {
        this(alias, T_PROD_INFO);
    }

    private TProdInfo(String alias, Table<TProdInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TProdInfo(String alias, Table<TProdInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TProdInfoRecord> getPrimaryKey() {
        return Keys.KEY_T_PROD_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TProdInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TProdInfoRecord>>asList(Keys.KEY_T_PROD_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdInfo as(String alias) {
        return new TProdInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TProdInfo rename(String name) {
        return new TProdInfo(name, null);
    }
}
