/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TSimilarklineStockRecord;


/**
 * 相似k线股票信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSimilarklineStock extends TableImpl<TSimilarklineStockRecord> {

    private static final long serialVersionUID = -881199602;

    /**
     * The reference instance of <code>datasync.t_similarkline_stock</code>
     */
    public static final TSimilarklineStock T_SIMILARKLINE_STOCK = new TSimilarklineStock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSimilarklineStockRecord> getRecordType() {
        return TSimilarklineStockRecord.class;
    }

    /**
     * The column <code>datasync.t_similarkline_stock.release_time</code>. 发布时间
     */
    public final TableField<TSimilarklineStockRecord, Timestamp> RELEASE_TIME = createField("release_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "发布时间");

    /**
     * The column <code>datasync.t_similarkline_stock.trade_date</code>. 交易日期
     */
    public final TableField<TSimilarklineStockRecord, Date> TRADE_DATE = createField("trade_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "交易日期");

    /**
     * The column <code>datasync.t_similarkline_stock.stock_code</code>. 股票代码
     */
    public final TableField<TSimilarklineStockRecord, String> STOCK_CODE = createField("stock_code", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "股票代码");

    /**
     * The column <code>datasync.t_similarkline_stock.stock_name</code>. 股票名称
     */
    public final TableField<TSimilarklineStockRecord, String> STOCK_NAME = createField("stock_name", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "股票名称");

    /**
     * The column <code>datasync.t_similarkline_stock.market_code</code>. 市场代码
     */
    public final TableField<TSimilarklineStockRecord, Short> MARKET_CODE = createField("market_code", org.jooq.impl.SQLDataType.SMALLINT, this, "市场代码");

    /**
     * The column <code>datasync.t_similarkline_stock.closely_stock_code</code>. 相似股票代码
     */
    public final TableField<TSimilarklineStockRecord, String> CLOSELY_STOCK_CODE = createField("closely_stock_code", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "相似股票代码");

    /**
     * The column <code>datasync.t_similarkline_stock.closely_stock_name</code>. 相似股票名称
     */
    public final TableField<TSimilarklineStockRecord, String> CLOSELY_STOCK_NAME = createField("closely_stock_name", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "相似股票名称");

    /**
     * The column <code>datasync.t_similarkline_stock.kline_start_date</code>. k线开始日期
     */
    public final TableField<TSimilarklineStockRecord, Date> KLINE_START_DATE = createField("kline_start_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "k线开始日期");

    /**
     * The column <code>datasync.t_similarkline_stock.kline_end_date</code>. k线结束日期
     */
    public final TableField<TSimilarklineStockRecord, Date> KLINE_END_DATE = createField("kline_end_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "k线结束日期");

    /**
     * The column <code>datasync.t_similarkline_stock.similar_rate</code>. 相似度
     */
    public final TableField<TSimilarklineStockRecord, String> SIMILAR_RATE = createField("similar_rate", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "相似度");

    /**
     * The column <code>datasync.t_similarkline_stock.rise_chance</code>. 上涨概率
     */
    public final TableField<TSimilarklineStockRecord, String> RISE_CHANCE = createField("rise_chance", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "上涨概率");

    /**
     * The column <code>datasync.t_similarkline_stock.marketinfo_json</code>. 行情信息json串（包含klinestartdate和klineenddate内的该股票行情信息）
     */
    public final TableField<TSimilarklineStockRecord, String> MARKETINFO_JSON = createField("marketinfo_json", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "行情信息json串（包含klinestartdate和klineenddate内的该股票行情信息）");

    /**
     * The column <code>datasync.t_similarkline_stock.ext_param</code>. 扩展字段
     */
    public final TableField<TSimilarklineStockRecord, String> EXT_PARAM = createField("ext_param", org.jooq.impl.SQLDataType.CLOB, this, "扩展字段");

    /**
     * The column <code>datasync.t_similarkline_stock.similar_up</code>. 相似上涨股票数
     */
    public final TableField<TSimilarklineStockRecord, Integer> SIMILAR_UP = createField("similar_up", org.jooq.impl.SQLDataType.INTEGER, this, "相似上涨股票数");

    /**
     * The column <code>datasync.t_similarkline_stock.similar_down</code>. 相似下跌股票数
     */
    public final TableField<TSimilarklineStockRecord, Integer> SIMILAR_DOWN = createField("similar_down", org.jooq.impl.SQLDataType.INTEGER, this, "相似下跌股票数");

    /**
     * Create a <code>datasync.t_similarkline_stock</code> table reference
     */
    public TSimilarklineStock() {
        this("t_similarkline_stock", null);
    }

    /**
     * Create an aliased <code>datasync.t_similarkline_stock</code> table reference
     */
    public TSimilarklineStock(String alias) {
        this(alias, T_SIMILARKLINE_STOCK);
    }

    private TSimilarklineStock(String alias, Table<TSimilarklineStockRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSimilarklineStock(String alias, Table<TSimilarklineStockRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "相似k线股票信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TSimilarklineStockRecord> getPrimaryKey() {
        return Keys.KEY_T_SIMILARKLINE_STOCK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TSimilarklineStockRecord>> getKeys() {
        return Arrays.<UniqueKey<TSimilarklineStockRecord>>asList(Keys.KEY_T_SIMILARKLINE_STOCK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStock as(String alias) {
        return new TSimilarklineStock(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSimilarklineStock rename(String name) {
        return new TSimilarklineStock(name, null);
    }
}
