/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entry.mysql.Datasync;
import test.boot.entry.mysql.Keys;
import test.boot.entry.mysql.tables.records.TTopxStockinfoRecord;


/**
 * topx股票信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTopxStockinfo extends TableImpl<TTopxStockinfoRecord> {

    private static final long serialVersionUID = 1122810394;

    /**
     * The reference instance of <code>datasync.t_topx_stockinfo</code>
     */
    public static final TTopxStockinfo T_TOPX_STOCKINFO = new TTopxStockinfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTopxStockinfoRecord> getRecordType() {
        return TTopxStockinfoRecord.class;
    }

    /**
     * The column <code>datasync.t_topx_stockinfo.release_time</code>. 发布时间
     */
    public final TableField<TTopxStockinfoRecord, Timestamp> RELEASE_TIME = createField("release_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "发布时间");

    /**
     * The column <code>datasync.t_topx_stockinfo.type</code>. topx类型（1：上涨概率最大的股票）
     */
    public final TableField<TTopxStockinfoRecord, Short> TYPE = createField("type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "topx类型（1：上涨概率最大的股票）");

    /**
     * The column <code>datasync.t_topx_stockinfo.sub_type</code>. 子类别（0，全市场，其他值具体行业）
     */
    public final TableField<TTopxStockinfoRecord, String> SUB_TYPE = createField("sub_type", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "子类别（0，全市场，其他值具体行业）");

    /**
     * The column <code>datasync.t_topx_stockinfo.trade_date</code>. 交易日期
     */
    public final TableField<TTopxStockinfoRecord, Date> TRADE_DATE = createField("trade_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "交易日期");

    /**
     * The column <code>datasync.t_topx_stockinfo.stock_code</code>. 股票代码
     */
    public final TableField<TTopxStockinfoRecord, String> STOCK_CODE = createField("stock_code", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "股票代码");

    /**
     * The column <code>datasync.t_topx_stockinfo.stock_name</code>. 股票名称
     */
    public final TableField<TTopxStockinfoRecord, String> STOCK_NAME = createField("stock_name", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "股票名称");

    /**
     * The column <code>datasync.t_topx_stockinfo.stock_price</code>. 股票价格
     */
    public final TableField<TTopxStockinfoRecord, BigDecimal> STOCK_PRICE = createField("stock_price", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "股票价格");

    /**
     * The column <code>datasync.t_topx_stockinfo.growth_rate</code>. 涨跌幅
     */
    public final TableField<TTopxStockinfoRecord, String> GROWTH_RATE = createField("growth_rate", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "涨跌幅");

    /**
     * The column <code>datasync.t_topx_stockinfo.market_value</code>. 股票市值
     */
    public final TableField<TTopxStockinfoRecord, String> MARKET_VALUE = createField("market_value", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "股票市值");

    /**
     * The column <code>datasync.t_topx_stockinfo.rise_chance</code>. 上涨概率
     */
    public final TableField<TTopxStockinfoRecord, String> RISE_CHANCE = createField("rise_chance", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "上涨概率");

    /**
     * The column <code>datasync.t_topx_stockinfo.industry</code>. 所属行业
     */
    public final TableField<TTopxStockinfoRecord, String> INDUSTRY = createField("industry", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "所属行业");

    /**
     * The column <code>datasync.t_topx_stockinfo.ext_param</code>. 扩展字段（保留）
     */
    public final TableField<TTopxStockinfoRecord, String> EXT_PARAM = createField("ext_param", org.jooq.impl.SQLDataType.CLOB, this, "扩展字段（保留）");

    /**
     * The column <code>datasync.t_topx_stockinfo.trunover_rate</code>. 换手率
     */
    public final TableField<TTopxStockinfoRecord, String> TRUNOVER_RATE = createField("trunover_rate", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "换手率");

    /**
     * The column <code>datasync.t_topx_stockinfo.growth</code>.
     */
    public final TableField<TTopxStockinfoRecord, String> GROWTH = createField("growth", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>datasync.t_topx_stockinfo.avg_ratio</code>.
     */
    public final TableField<TTopxStockinfoRecord, String> AVG_RATIO = createField("avg_ratio", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>datasync.t_topx_stockinfo.similar_up</code>. 相似上涨股票数
     */
    public final TableField<TTopxStockinfoRecord, Integer> SIMILAR_UP = createField("similar_up", org.jooq.impl.SQLDataType.INTEGER, this, "相似上涨股票数");

    /**
     * The column <code>datasync.t_topx_stockinfo.similar_down</code>. 相似下跌股票数
     */
    public final TableField<TTopxStockinfoRecord, Integer> SIMILAR_DOWN = createField("similar_down", org.jooq.impl.SQLDataType.INTEGER, this, "相似下跌股票数");

    /**
     * The column <code>datasync.t_topx_stockinfo.update_time</code>. 更新时间
     */
    public final TableField<TTopxStockinfoRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>datasync.t_topx_stockinfo</code> table reference
     */
    public TTopxStockinfo() {
        this("t_topx_stockinfo", null);
    }

    /**
     * Create an aliased <code>datasync.t_topx_stockinfo</code> table reference
     */
    public TTopxStockinfo(String alias) {
        this(alias, T_TOPX_STOCKINFO);
    }

    private TTopxStockinfo(String alias, Table<TTopxStockinfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TTopxStockinfo(String alias, Table<TTopxStockinfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "topx股票信息");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Datasync.DATASYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TTopxStockinfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TTopxStockinfoRecord>>asList(Keys.KEY_T_TOPX_STOCKINFO_IDX1_T_TOPX_STOCKINFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTopxStockinfo as(String alias) {
        return new TTopxStockinfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTopxStockinfo rename(String name) {
        return new TTopxStockinfo(name, null);
    }
}
