# H2 Configuration
spring:
  datasource:
    url: jdbc:h2:./code
    driver-class-name: org.h2.Driver
    username: root
    password: root
    # Hikari DateSource
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: true
# charset
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
