/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.boot.entity.Keys;
import test.boot.entity.Public;
import test.boot.entity.tables.records.TemplateGroupTemplateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateGroupTemplate extends TableImpl<TemplateGroupTemplateRecord> {

    private static final long serialVersionUID = 1112357481;

    /**
     * The reference instance of <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE</code>
     */
    public static final TemplateGroupTemplate R_TEMPLATE_GROUP_TEMPLATE = new TemplateGroupTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TemplateGroupTemplateRecord> getRecordType() {
        return TemplateGroupTemplateRecord.class;
    }

    /**
     * The column <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.ID</code>.
     */
    public final TableField<TemplateGroupTemplateRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3FABB1D1_1614_41BB_BB52_9131E25FD8DE)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.TG_ID</code>.
     */
    public final TableField<TemplateGroupTemplateRecord, Integer> TG_ID = createField("TG_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.T_ID</code>.
     */
    public final TableField<TemplateGroupTemplateRecord, Integer> T_ID = createField("T_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE</code> table reference
     */
    public TemplateGroupTemplate() {
        this("R_TEMPLATE_GROUP_TEMPLATE", null);
    }

    /**
     * Create an aliased <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE</code> table reference
     */
    public TemplateGroupTemplate(String alias) {
        this(alias, R_TEMPLATE_GROUP_TEMPLATE);
    }

    private TemplateGroupTemplate(String alias, Table<TemplateGroupTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private TemplateGroupTemplate(String alias, Table<TemplateGroupTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TemplateGroupTemplateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_R_TEMPLATE_GROUP_TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TemplateGroupTemplateRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TemplateGroupTemplateRecord>> getKeys() {
        return Arrays.<UniqueKey<TemplateGroupTemplateRecord>>asList(Keys.CONSTRAINT_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TemplateGroupTemplateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TemplateGroupTemplateRecord, ?>>asList(Keys.CONSTRAINT_4D, Keys.CONSTRAINT_4D8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateGroupTemplate as(String alias) {
        return new TemplateGroupTemplate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateGroupTemplate rename(String name) {
        return new TemplateGroupTemplate(name, null);
    }
}
