/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Datasource implements Serializable {

    private static final long serialVersionUID = 1043480889;

    private Integer id;
    private String  url;
    private String  username;
    private String  password;
    private String  name;

    public Datasource() {}

    public Datasource(Datasource value) {
        this.id = value.id;
        this.url = value.url;
        this.username = value.username;
        this.password = value.password;
        this.name = value.name;
    }

    public Datasource(
        Integer id,
        String  url,
        String  username,
        String  password,
        String  name
    ) {
        this.id = id;
        this.url = url;
        this.username = username;
        this.password = password;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Datasource (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
