/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Template implements Serializable {

    private static final long serialVersionUID = 1687350414;

    private Integer id;
    private String  content;
    private String  name;
    private String  fileName;
    private String  filePath;
    private String  parameters;

    public Template() {}

    public Template(Template value) {
        this.id = value.id;
        this.content = value.content;
        this.name = value.name;
        this.fileName = value.fileName;
        this.filePath = value.filePath;
        this.parameters = value.parameters;
    }

    public Template(
        Integer id,
        String  content,
        String  name,
        String  fileName,
        String  filePath,
        String  parameters
    ) {
        this.id = id;
        this.content = content;
        this.name = name;
        this.fileName = fileName;
        this.filePath = filePath;
        this.parameters = parameters;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getParameters() {
        return this.parameters;
    }

    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Template (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(name);
        sb.append(", ").append(fileName);
        sb.append(", ").append(filePath);
        sb.append(", ").append(parameters);

        sb.append(")");
        return sb.toString();
    }
}
