/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Template implements Serializable {

    private static final long serialVersionUID = 366258373;

    private Integer id;
    private String  content;
    private String  name;
    private String  tags;
    private String  fileName;
    private String  filepath;

    public Template() {}

    public Template(Template value) {
        this.id = value.id;
        this.content = value.content;
        this.name = value.name;
        this.tags = value.tags;
        this.fileName = value.fileName;
        this.filepath = value.filepath;
    }

    public Template(
        Integer id,
        String  content,
        String  name,
        String  tags,
        String  fileName,
        String  filepath
    ) {
        this.id = id;
        this.content = content;
        this.name = name;
        this.tags = tags;
        this.fileName = fileName;
        this.filepath = filepath;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilepath() {
        return this.filepath;
    }

    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Template (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(name);
        sb.append(", ").append(tags);
        sb.append(", ").append(fileName);
        sb.append(", ").append(filepath);

        sb.append(")");
        return sb.toString();
    }
}
