/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateGroupTemplate implements Serializable {

    private static final long serialVersionUID = -1903320481;

    private Integer id;
    private Integer tgId;
    private Integer tId;

    public TemplateGroupTemplate() {}

    public TemplateGroupTemplate(TemplateGroupTemplate value) {
        this.id = value.id;
        this.tgId = value.tgId;
        this.tId = value.tId;
    }

    public TemplateGroupTemplate(
        Integer id,
        Integer tgId,
        Integer tId
    ) {
        this.id = id;
        this.tgId = tgId;
        this.tId = tId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTgId() {
        return this.tgId;
    }

    public void setTgId(Integer tgId) {
        this.tgId = tgId;
    }

    public Integer getTId() {
        return this.tId;
    }

    public void setTId(Integer tId) {
        this.tId = tId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TemplateGroupTemplate (");

        sb.append(id);
        sb.append(", ").append(tgId);
        sb.append(", ").append(tId);

        sb.append(")");
        return sb.toString();
    }
}
