/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import test.boot.entry.mysql.tables.TAccountMark;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMarkRecord extends UpdatableRecordImpl<TAccountMarkRecord> implements Record4<String, UInteger, UInteger, Timestamp> {

    private static final long serialVersionUID = 1000886236;

    /**
     * Setter for <code>datasync.t_account_mark.FUND_ACCOUNT</code>.
     */
    public void setFundAccount(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark.FUND_ACCOUNT</code>.
     */
    public String getFundAccount() {
        return (String) get(0);
    }

    /**
     * Setter for <code>datasync.t_account_mark.MARK_TYPE</code>. 标签类型
     */
    public void setMarkType(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark.MARK_TYPE</code>. 标签类型
     */
    public UInteger getMarkType() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>datasync.t_account_mark.MARK_VALUE</code>. 用户标签
     */
    public void setMarkValue(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark.MARK_VALUE</code>. 用户标签
     */
    public UInteger getMarkValue() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>datasync.t_account_mark.UPDATE_TIME</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark.UPDATE_TIME</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, UInteger, UInteger, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, UInteger, UInteger, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TAccountMark.T_ACCOUNT_MARK.FUND_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TAccountMark.T_ACCOUNT_MARK.MARK_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return TAccountMark.T_ACCOUNT_MARK.MARK_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TAccountMark.T_ACCOUNT_MARK.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFundAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getMarkType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getMarkValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkRecord value1(String value) {
        setFundAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkRecord value2(UInteger value) {
        setMarkType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkRecord value3(UInteger value) {
        setMarkValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkRecord value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkRecord values(String value1, UInteger value2, UInteger value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAccountMarkRecord
     */
    public TAccountMarkRecord() {
        super(TAccountMark.T_ACCOUNT_MARK);
    }

    /**
     * Create a detached, initialised TAccountMarkRecord
     */
    public TAccountMarkRecord(String fundAccount, UInteger markType, UInteger markValue, Timestamp updateTime) {
        super(TAccountMark.T_ACCOUNT_MARK);

        set(0, fundAccount);
        set(1, markType);
        set(2, markValue);
        set(3, updateTime);
    }
}
