/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import test.boot.entry.mysql.tables.TAccountMarkProdInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMarkProdInfoRecord extends UpdatableRecordImpl<TAccountMarkProdInfoRecord> implements Record4<UInteger, String, Timestamp, String> {

    private static final long serialVersionUID = -497386883;

    /**
     * Setter for <code>datasync.t_account_mark_prod_info.PROD_TYPE</code>. 标签类别
     */
    public void setProdType(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark_prod_info.PROD_TYPE</code>. 标签类别
     */
    public UInteger getProdType() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>datasync.t_account_mark_prod_info.PROD_CODE</code>. 产品代码
     */
    public void setProdCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark_prod_info.PROD_CODE</code>. 产品代码
     */
    public String getProdCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>datasync.t_account_mark_prod_info.UPDATE_TIME</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark_prod_info.UPDATE_TIME</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>datasync.t_account_mark_prod_info.PROD_CATEGORY</code>. 产品类别
     */
    public void setProdCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_account_mark_prod_info.PROD_CATEGORY</code>. 产品类别
     */
    public String getProdCategory() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, Timestamp, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, Timestamp, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO.PROD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO.PROD_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO.PROD_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getProdType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProdCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProdCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkProdInfoRecord value1(UInteger value) {
        setProdType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkProdInfoRecord value2(String value) {
        setProdCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkProdInfoRecord value3(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkProdInfoRecord value4(String value) {
        setProdCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMarkProdInfoRecord values(UInteger value1, String value2, Timestamp value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAccountMarkProdInfoRecord
     */
    public TAccountMarkProdInfoRecord() {
        super(TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO);
    }

    /**
     * Create a detached, initialised TAccountMarkProdInfoRecord
     */
    public TAccountMarkProdInfoRecord(UInteger prodType, String prodCode, Timestamp updateTime, String prodCategory) {
        super(TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO);

        set(0, prodType);
        set(1, prodCode);
        set(2, updateTime);
        set(3, prodCategory);
    }
}
