/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TAccountMot;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMotRecord extends UpdatableRecordImpl<TAccountMotRecord> implements Record5<String, String, BigDecimal, String, Timestamp> {

    private static final long serialVersionUID = 1463006151;

    /**
     * Setter for <code>datasync.t_account_mot.FUND_ACCOUNT</code>.
     */
    public void setFundAccount(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_account_mot.FUND_ACCOUNT</code>.
     */
    public String getFundAccount() {
        return (String) get(0);
    }

    /**
     * Setter for <code>datasync.t_account_mot.MOT_MARK</code>. 用户标签
     */
    public void setMotMark(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_account_mot.MOT_MARK</code>. 用户标签
     */
    public String getMotMark() {
        return (String) get(1);
    }

    /**
     * Setter for <code>datasync.t_account_mot.MOT_LEVEL</code>. MOT等级
     */
    public void setMotLevel(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_account_mot.MOT_LEVEL</code>. MOT等级
     */
    public BigDecimal getMotLevel() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>datasync.t_account_mot.MOT_EXTEND</code>. MOT详情,JSON格式
     */
    public void setMotExtend(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_account_mot.MOT_EXTEND</code>. MOT详情,JSON格式
     */
    public String getMotExtend() {
        return (String) get(3);
    }

    /**
     * Setter for <code>datasync.t_account_mot.UPDATE_TIME</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_account_mot.UPDATE_TIME</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, BigDecimal, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, BigDecimal, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TAccountMot.T_ACCOUNT_MOT.FUND_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TAccountMot.T_ACCOUNT_MOT.MOT_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TAccountMot.T_ACCOUNT_MOT.MOT_LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TAccountMot.T_ACCOUNT_MOT.MOT_EXTEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TAccountMot.T_ACCOUNT_MOT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFundAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMotMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getMotLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMotExtend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMotRecord value1(String value) {
        setFundAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMotRecord value2(String value) {
        setMotMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMotRecord value3(BigDecimal value) {
        setMotLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMotRecord value4(String value) {
        setMotExtend(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMotRecord value5(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountMotRecord values(String value1, String value2, BigDecimal value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAccountMotRecord
     */
    public TAccountMotRecord() {
        super(TAccountMot.T_ACCOUNT_MOT);
    }

    /**
     * Create a detached, initialised TAccountMotRecord
     */
    public TAccountMotRecord(String fundAccount, String motMark, BigDecimal motLevel, String motExtend, Timestamp updateTime) {
        super(TAccountMot.T_ACCOUNT_MOT);

        set(0, fundAccount);
        set(1, motMark);
        set(2, motLevel);
        set(3, motExtend);
        set(4, updateTime);
    }
}
