/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TAccountAsset;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountAssetRecord extends UpdatableRecordImpl<TAccountAssetRecord> implements Record7<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -582002392;

    /**
     * Setter for <code>datasync.t_account_asset.FUND_ACCOUNT</code>. 资金账号
     */
    public void setFundAccount(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.FUND_ACCOUNT</code>. 资金账号
     */
    public String getFundAccount() {
        return (String) get(0);
    }

    /**
     * Setter for <code>datasync.t_account_asset.ORG_ID</code>. 营业部ID
     */
    public void setOrgId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.ORG_ID</code>. 营业部ID
     */
    public String getOrgId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>datasync.t_account_asset.INTER_ASSET</code>. 体内资产
     */
    public void setInterAsset(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.INTER_ASSET</code>. 体内资产
     */
    public BigDecimal getInterAsset() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>datasync.t_account_asset.OUTER_ASSET</code>. 体外资产
     */
    public void setOuterAsset(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.OUTER_ASSET</code>. 体外资产
     */
    public BigDecimal getOuterAsset() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>datasync.t_account_asset.TOTAL_ASSET</code>. 总资产
     */
    public void setTotalAsset(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.TOTAL_ASSET</code>. 总资产
     */
    public BigDecimal getTotalAsset() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>datasync.t_account_asset.EXPIRE_ASSET</code>. 到期资产
     */
    public void setExpireAsset(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.EXPIRE_ASSET</code>. 到期资产
     */
    public BigDecimal getExpireAsset() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>datasync.t_account_asset.UPDATE_TIME</code>. 更新日期
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>datasync.t_account_asset.UPDATE_TIME</code>. 更新日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TAccountAsset.T_ACCOUNT_ASSET.FUND_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TAccountAsset.T_ACCOUNT_ASSET.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TAccountAsset.T_ACCOUNT_ASSET.INTER_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TAccountAsset.T_ACCOUNT_ASSET.OUTER_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return TAccountAsset.T_ACCOUNT_ASSET.TOTAL_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TAccountAsset.T_ACCOUNT_ASSET.EXPIRE_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TAccountAsset.T_ACCOUNT_ASSET.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFundAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getInterAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getOuterAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getTotalAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getExpireAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value1(String value) {
        setFundAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value2(String value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value3(BigDecimal value) {
        setInterAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value4(BigDecimal value) {
        setOuterAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value5(BigDecimal value) {
        setTotalAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value6(BigDecimal value) {
        setExpireAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAccountAssetRecord values(String value1, String value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAccountAssetRecord
     */
    public TAccountAssetRecord() {
        super(TAccountAsset.T_ACCOUNT_ASSET);
    }

    /**
     * Create a detached, initialised TAccountAssetRecord
     */
    public TAccountAssetRecord(String fundAccount, String orgId, BigDecimal interAsset, BigDecimal outerAsset, BigDecimal totalAsset, BigDecimal expireAsset, Timestamp updateTime) {
        super(TAccountAsset.T_ACCOUNT_ASSET);

        set(0, fundAccount);
        set(1, orgId);
        set(2, interAsset);
        set(3, outerAsset);
        set(4, totalAsset);
        set(5, expireAsset);
        set(6, updateTime);
    }
}
