/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TDictLvl2;


/**
 * 二级数据字典
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDictLvl2Record extends UpdatableRecordImpl<TDictLvl2Record> implements Record5<String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -540308180;

    /**
     * Setter for <code>datasync.t_dict_lvl2.dict_item</code>. 字典项
     */
    public void setDictItem(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_dict_lvl2.dict_item</code>. 字典项
     */
    public String getDictItem() {
        return (String) get(0);
    }

    /**
     * Setter for <code>datasync.t_dict_lvl2.dict_key</code>. 字典项键名
     */
    public void setDictKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_dict_lvl2.dict_key</code>. 字典项键名
     */
    public String getDictKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>datasync.t_dict_lvl2.dict_value</code>. 字典项键值
     */
    public void setDictValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_dict_lvl2.dict_value</code>. 字典项键值
     */
    public String getDictValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>datasync.t_dict_lvl2.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_dict_lvl2.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>datasync.t_dict_lvl2.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_dict_lvl2.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TDictLvl2.T_DICT_LVL2.DICT_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDictLvl2.T_DICT_LVL2.DICT_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TDictLvl2.T_DICT_LVL2.DICT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TDictLvl2.T_DICT_LVL2.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TDictLvl2.T_DICT_LVL2.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDictItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDictKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDictValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Record value1(String value) {
        setDictItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Record value2(String value) {
        setDictKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Record value3(String value) {
        setDictValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Record value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Record value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDictLvl2Record values(String value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDictLvl2Record
     */
    public TDictLvl2Record() {
        super(TDictLvl2.T_DICT_LVL2);
    }

    /**
     * Create a detached, initialised TDictLvl2Record
     */
    public TDictLvl2Record(String dictItem, String dictKey, String dictValue, Timestamp updateTime, Timestamp createTime) {
        super(TDictLvl2.T_DICT_LVL2);

        set(0, dictItem);
        set(1, dictKey);
        set(2, dictValue);
        set(3, updateTime);
        set(4, createTime);
    }
}
