/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TIndexSignal;


/**
 * 指数信号信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndexSignalRecord extends UpdatableRecordImpl<TIndexSignalRecord> implements Record6<Timestamp, Date, String, Short, String, String> {

    private static final long serialVersionUID = -1043514032;

    /**
     * Setter for <code>datasync.t_index_signal.release_time</code>. 发布时间
     */
    public void setReleaseTime(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_index_signal.release_time</code>. 发布时间
     */
    public Timestamp getReleaseTime() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>datasync.t_index_signal.trade_date</code>. 交易日期
     */
    public void setTradeDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_index_signal.trade_date</code>. 交易日期
     */
    public Date getTradeDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>datasync.t_index_signal.signal</code>. 信号
     */
    public void setSignal(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_index_signal.signal</code>. 信号
     */
    public String getSignal() {
        return (String) get(2);
    }

    /**
     * Setter for <code>datasync.t_index_signal.signal_type</code>. 信号类别（1：变盘信号）
     */
    public void setSignalType(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_index_signal.signal_type</code>. 信号类别（1：变盘信号）
     */
    public Short getSignalType() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>datasync.t_index_signal.comment</code>. 点评
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_index_signal.comment</code>. 点评
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>datasync.t_index_signal.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>datasync.t_index_signal.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Date> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Timestamp, Date, String, Short, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Timestamp, Date, String, Short, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return TIndexSignal.T_INDEX_SIGNAL.RELEASE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return TIndexSignal.T_INDEX_SIGNAL.TRADE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TIndexSignal.T_INDEX_SIGNAL.SIGNAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return TIndexSignal.T_INDEX_SIGNAL.SIGNAL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TIndexSignal.T_INDEX_SIGNAL.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TIndexSignal.T_INDEX_SIGNAL.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getTradeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSignal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getSignalType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord value1(Timestamp value) {
        setReleaseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord value2(Date value) {
        setTradeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord value3(String value) {
        setSignal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord value4(Short value) {
        setSignalType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord value5(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexSignalRecord values(Timestamp value1, Date value2, String value3, Short value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TIndexSignalRecord
     */
    public TIndexSignalRecord() {
        super(TIndexSignal.T_INDEX_SIGNAL);
    }

    /**
     * Create a detached, initialised TIndexSignalRecord
     */
    public TIndexSignalRecord(Timestamp releaseTime, Date tradeDate, String signal, Short signalType, String comment, String remark) {
        super(TIndexSignal.T_INDEX_SIGNAL);

        set(0, releaseTime);
        set(1, tradeDate);
        set(2, signal);
        set(3, signalType);
        set(4, comment);
        set(5, remark);
    }
}
