/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TIndexHistperf;


/**
 * 历史预警后大盘指数表现信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndexHistperfRecord extends UpdatableRecordImpl<TIndexHistperfRecord> implements Record9<Timestamp, Date, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1792379754;

    /**
     * Setter for <code>datasync.t_index_histperf.release_time</code>. 发布时间
     */
    public void setReleaseTime(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.release_time</code>. 发布时间
     */
    public Timestamp getReleaseTime() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.trade_date</code>. 交易日期
     */
    public void setTradeDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.trade_date</code>. 交易日期
     */
    public Date getTradeDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.index_code</code>. 指数类型代码（1-上证， 2-沪深300， 3-中证500， 4-深证）
     */
    public void setIndexCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.index_code</code>. 指数类型代码（1-上证， 2-沪深300， 3-中证500， 4-深证）
     */
    public String getIndexCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.index_name</code>. 指数名称（上证，深证，等）
     */
    public void setIndexName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.index_name</code>. 指数名称（上证，深证，等）
     */
    public String getIndexName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.close_price_before</code>. 当日股票收盘价
     */
    public void setClosePriceBefore(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.close_price_before</code>. 当日股票收盘价
     */
    public String getClosePriceBefore() {
        return (String) get(4);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.close_price_after</code>. 30日后指数收盘价
     */
    public void setClosePriceAfter(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.close_price_after</code>. 30日后指数收盘价
     */
    public String getClosePriceAfter() {
        return (String) get(5);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.net_ratio</code>. 涨跌额
     */
    public void setNetRatio(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.net_ratio</code>. 涨跌额
     */
    public String getNetRatio() {
        return (String) get(6);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.ratio</code>. 涨跌幅
     */
    public void setRatio(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.ratio</code>. 涨跌幅
     */
    public String getRatio() {
        return (String) get(7);
    }

    /**
     * Setter for <code>datasync.t_index_histperf.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>datasync.t_index_histperf.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Date, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Timestamp, Date, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Timestamp, Date, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return TIndexHistperf.T_INDEX_HISTPERF.RELEASE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return TIndexHistperf.T_INDEX_HISTPERF.TRADE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TIndexHistperf.T_INDEX_HISTPERF.INDEX_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TIndexHistperf.T_INDEX_HISTPERF.INDEX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TIndexHistperf.T_INDEX_HISTPERF.CLOSE_PRICE_BEFORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TIndexHistperf.T_INDEX_HISTPERF.CLOSE_PRICE_AFTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TIndexHistperf.T_INDEX_HISTPERF.NET_RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TIndexHistperf.T_INDEX_HISTPERF.RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TIndexHistperf.T_INDEX_HISTPERF.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getTradeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIndexCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getClosePriceBefore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getClosePriceAfter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNetRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value1(Timestamp value) {
        setReleaseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value2(Date value) {
        setTradeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value3(String value) {
        setIndexCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value4(String value) {
        setIndexName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value5(String value) {
        setClosePriceBefore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value6(String value) {
        setClosePriceAfter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value7(String value) {
        setNetRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value8(String value) {
        setRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord value9(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TIndexHistperfRecord values(Timestamp value1, Date value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TIndexHistperfRecord
     */
    public TIndexHistperfRecord() {
        super(TIndexHistperf.T_INDEX_HISTPERF);
    }

    /**
     * Create a detached, initialised TIndexHistperfRecord
     */
    public TIndexHistperfRecord(Timestamp releaseTime, Date tradeDate, String indexCode, String indexName, String closePriceBefore, String closePriceAfter, String netRatio, String ratio, String remark) {
        super(TIndexHistperf.T_INDEX_HISTPERF);

        set(0, releaseTime);
        set(1, tradeDate);
        set(2, indexCode);
        set(3, indexName);
        set(4, closePriceBefore);
        set(5, closePriceAfter);
        set(6, netRatio);
        set(7, ratio);
        set(8, remark);
    }
}
