/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TProdInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProdInfoRecord extends UpdatableRecordImpl<TProdInfoRecord> implements Record2<String, Timestamp> {

    private static final long serialVersionUID = 839976373;

    /**
     * Setter for <code>datasync.t_prod_info.PROD_CODE</code>. 产品代码
     */
    public void setProdCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_prod_info.PROD_CODE</code>. 产品代码
     */
    public String getProdCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>datasync.t_prod_info.UPDATE_TIME</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_prod_info.UPDATE_TIME</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TProdInfo.T_PROD_INFO.PROD_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TProdInfo.T_PROD_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProdCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdInfoRecord value1(String value) {
        setProdCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdInfoRecord value2(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdInfoRecord values(String value1, Timestamp value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TProdInfoRecord
     */
    public TProdInfoRecord() {
        super(TProdInfo.T_PROD_INFO);
    }

    /**
     * Create a detached, initialised TProdInfoRecord
     */
    public TProdInfoRecord(String prodCode, Timestamp updateTime) {
        super(TProdInfo.T_PROD_INFO);

        set(0, prodCode);
        set(1, updateTime);
    }
}
