/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Record2;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import test.boot.entry.mysql.tables.TProdAccountInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProdAccountInfoRecord extends UpdatableRecordImpl<TProdAccountInfoRecord> implements Record18<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Timestamp, String, UInteger> {

    private static final long serialVersionUID = -299253054;

    /**
     * Setter for <code>datasync.t_prod_account_info.PROD_CODE</code>. 产品编号
     */
    public void setProdCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.PROD_CODE</code>. 产品编号
     */
    public String getProdCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.FUND_ACCOUNT</code>. 资金账号
     */
    public void setFundAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.FUND_ACCOUNT</code>. 资金账号
     */
    public String getFundAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.MATCH_RATIO</code>. 匹配度
     */
    public void setMatchRatio(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.MATCH_RATIO</code>. 匹配度
     */
    public BigDecimal getMatchRatio() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.INTER_ASSET</code>. 体内资产
     */
    public void setInterAsset(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.INTER_ASSET</code>. 体内资产
     */
    public BigDecimal getInterAsset() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.OUTER_ASSET</code>. 体外资产
     */
    public void setOuterAsset(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.OUTER_ASSET</code>. 体外资产
     */
    public BigDecimal getOuterAsset() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.TOTAL_ASSET</code>. 总资产
     */
    public void setTotalAsset(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.TOTAL_ASSET</code>. 总资产
     */
    public BigDecimal getTotalAsset() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.TOTAL_ASSET_MARK</code>. 总资产分值
     */
    public void setTotalAssetMark(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.TOTAL_ASSET_MARK</code>. 总资产分值
     */
    public BigDecimal getTotalAssetMark() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.EXPIRE_ASSET</code>. 到期资产资产
     */
    public void setExpireAsset(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.EXPIRE_ASSET</code>. 到期资产资产
     */
    public BigDecimal getExpireAsset() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.EXPIRE_ASSET_MARK</code>. 到期资产分值
     */
    public void setExpireAssetMark(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.EXPIRE_ASSET_MARK</code>. 到期资产分值
     */
    public BigDecimal getExpireAssetMark() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.HISTORY_MARK</code>. 同公司基金购买历史
     */
    public void setHistoryMark(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.HISTORY_MARK</code>. 同公司基金购买历史
     */
    public BigDecimal getHistoryMark() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.LAST_12_YIELD_RATIO</code>. 近12个月客户收益率
     */
    public void setLast_12YieldRatio(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.LAST_12_YIELD_RATIO</code>. 近12个月客户收益率
     */
    public BigDecimal getLast_12YieldRatio() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.YIELD_MARK</code>. 收益率分值
     */
    public void setYieldMark(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.YIELD_MARK</code>. 收益率分值
     */
    public BigDecimal getYieldMark() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.STOCK_TURN_RATIO</code>. 股票周转率
     */
    public void setStockTurnRatio(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.STOCK_TURN_RATIO</code>. 股票周转率
     */
    public BigDecimal getStockTurnRatio() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.STOCK_TURN_RATIO_MARK</code>. 股票周转率分值
     */
    public void setStockTurnRatioMark(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.STOCK_TURN_RATIO_MARK</code>. 股票周转率分值
     */
    public BigDecimal getStockTurnRatioMark() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.BUY_ABLE</code>. 购买可能性
     */
    public void setBuyAble(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.BUY_ABLE</code>. 购买可能性
     */
    public BigDecimal getBuyAble() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.UPDATE_TIME</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.UPDATE_TIME</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.ORG_ID</code>. 营业部编号
     */
    public void setOrgId(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.ORG_ID</code>. 营业部编号
     */
    public String getOrgId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>datasync.t_prod_account_info.HOLD_STATUS</code>. 持有状态
     */
    public void setHoldStatus(UInteger value) {
        set(17, value);
    }

    /**
     * Getter for <code>datasync.t_prod_account_info.HOLD_STATUS</code>. 持有状态
     */
    public UInteger getHoldStatus() {
        return (UInteger) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Timestamp, String, UInteger> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Timestamp, String, UInteger> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.PROD_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.FUND_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.MATCH_RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.INTER_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.OUTER_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.TOTAL_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.TOTAL_ASSET_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.EXPIRE_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.EXPIRE_ASSET_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.HISTORY_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.LAST_12_YIELD_RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.YIELD_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.STOCK_TURN_RATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field14() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.STOCK_TURN_RATIO_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.BUY_ABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field18() {
        return TProdAccountInfo.T_PROD_ACCOUNT_INFO.HOLD_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProdCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFundAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getMatchRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getInterAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getOuterAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getTotalAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getTotalAssetMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getExpireAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getExpireAssetMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getHistoryMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getLast_12YieldRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getYieldMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getStockTurnRatio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value14() {
        return getStockTurnRatioMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getBuyAble();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value18() {
        return getHoldStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value1(String value) {
        setProdCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value2(String value) {
        setFundAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value3(BigDecimal value) {
        setMatchRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value4(BigDecimal value) {
        setInterAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value5(BigDecimal value) {
        setOuterAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value6(BigDecimal value) {
        setTotalAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value7(BigDecimal value) {
        setTotalAssetMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value8(BigDecimal value) {
        setExpireAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value9(BigDecimal value) {
        setExpireAssetMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value10(BigDecimal value) {
        setHistoryMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value11(BigDecimal value) {
        setLast_12YieldRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value12(BigDecimal value) {
        setYieldMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value13(BigDecimal value) {
        setStockTurnRatio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value14(BigDecimal value) {
        setStockTurnRatioMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value15(BigDecimal value) {
        setBuyAble(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value16(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value17(String value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord value18(UInteger value) {
        setHoldStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProdAccountInfoRecord values(String value1, String value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, BigDecimal value14, BigDecimal value15, Timestamp value16, String value17, UInteger value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TProdAccountInfoRecord
     */
    public TProdAccountInfoRecord() {
        super(TProdAccountInfo.T_PROD_ACCOUNT_INFO);
    }

    /**
     * Create a detached, initialised TProdAccountInfoRecord
     */
    public TProdAccountInfoRecord(String prodCode, String fundAccount, BigDecimal matchRatio, BigDecimal interAsset, BigDecimal outerAsset, BigDecimal totalAsset, BigDecimal totalAssetMark, BigDecimal expireAsset, BigDecimal expireAssetMark, BigDecimal historyMark, BigDecimal last_12YieldRatio, BigDecimal yieldMark, BigDecimal stockTurnRatio, BigDecimal stockTurnRatioMark, BigDecimal buyAble, Timestamp updateTime, String orgId, UInteger holdStatus) {
        super(TProdAccountInfo.T_PROD_ACCOUNT_INFO);

        set(0, prodCode);
        set(1, fundAccount);
        set(2, matchRatio);
        set(3, interAsset);
        set(4, outerAsset);
        set(5, totalAsset);
        set(6, totalAssetMark);
        set(7, expireAsset);
        set(8, expireAssetMark);
        set(9, historyMark);
        set(10, last_12YieldRatio);
        set(11, yieldMark);
        set(12, stockTurnRatio);
        set(13, stockTurnRatioMark);
        set(14, buyAble);
        set(15, updateTime);
        set(16, orgId);
        set(17, holdStatus);
    }
}
