/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record3;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TSimilarklineStock;


/**
 * 相似k线股票信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSimilarklineStockRecord extends UpdatableRecordImpl<TSimilarklineStockRecord> implements Record15<Timestamp, Date, String, String, Short, String, String, Date, Date, String, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 364310390;

    /**
     * Setter for <code>datasync.t_similarkline_stock.release_time</code>. 发布时间
     */
    public void setReleaseTime(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.release_time</code>. 发布时间
     */
    public Timestamp getReleaseTime() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.trade_date</code>. 交易日期
     */
    public void setTradeDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.trade_date</code>. 交易日期
     */
    public Date getTradeDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.stock_code</code>. 股票代码
     */
    public void setStockCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.stock_code</code>. 股票代码
     */
    public String getStockCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.stock_name</code>. 股票名称
     */
    public void setStockName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.stock_name</code>. 股票名称
     */
    public String getStockName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.market_code</code>. 市场代码
     */
    public void setMarketCode(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.market_code</code>. 市场代码
     */
    public Short getMarketCode() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.closely_stock_code</code>. 相似股票代码
     */
    public void setCloselyStockCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.closely_stock_code</code>. 相似股票代码
     */
    public String getCloselyStockCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.closely_stock_name</code>. 相似股票名称
     */
    public void setCloselyStockName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.closely_stock_name</code>. 相似股票名称
     */
    public String getCloselyStockName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.kline_start_date</code>. k线开始日期
     */
    public void setKlineStartDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.kline_start_date</code>. k线开始日期
     */
    public Date getKlineStartDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.kline_end_date</code>. k线结束日期
     */
    public void setKlineEndDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.kline_end_date</code>. k线结束日期
     */
    public Date getKlineEndDate() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.similar_rate</code>. 相似度
     */
    public void setSimilarRate(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.similar_rate</code>. 相似度
     */
    public String getSimilarRate() {
        return (String) get(9);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.rise_chance</code>. 上涨概率
     */
    public void setRiseChance(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.rise_chance</code>. 上涨概率
     */
    public String getRiseChance() {
        return (String) get(10);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.marketinfo_json</code>. 行情信息json串（包含klinestartdate和klineenddate内的该股票行情信息）
     */
    public void setMarketinfoJson(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.marketinfo_json</code>. 行情信息json串（包含klinestartdate和klineenddate内的该股票行情信息）
     */
    public String getMarketinfoJson() {
        return (String) get(11);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.ext_param</code>. 扩展字段
     */
    public void setExtParam(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.ext_param</code>. 扩展字段
     */
    public String getExtParam() {
        return (String) get(12);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.similar_up</code>. 相似上涨股票数
     */
    public void setSimilarUp(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.similar_up</code>. 相似上涨股票数
     */
    public Integer getSimilarUp() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>datasync.t_similarkline_stock.similar_down</code>. 相似下跌股票数
     */
    public void setSimilarDown(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>datasync.t_similarkline_stock.similar_down</code>. 相似下跌股票数
     */
    public Integer getSimilarDown() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Date, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Timestamp, Date, String, String, Short, String, String, Date, Date, String, String, String, String, Integer, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Timestamp, Date, String, String, Short, String, String, Date, Date, String, String, String, String, Integer, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.RELEASE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.TRADE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.STOCK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.STOCK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.MARKET_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.CLOSELY_STOCK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.CLOSELY_STOCK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.KLINE_START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.KLINE_END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.SIMILAR_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.RISE_CHANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.MARKETINFO_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.EXT_PARAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.SIMILAR_UP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TSimilarklineStock.T_SIMILARKLINE_STOCK.SIMILAR_DOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getTradeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStockName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getMarketCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCloselyStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCloselyStockName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getKlineStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getKlineEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSimilarRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRiseChance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getMarketinfoJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getExtParam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getSimilarUp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getSimilarDown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value1(Timestamp value) {
        setReleaseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value2(Date value) {
        setTradeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value3(String value) {
        setStockCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value4(String value) {
        setStockName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value5(Short value) {
        setMarketCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value6(String value) {
        setCloselyStockCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value7(String value) {
        setCloselyStockName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value8(Date value) {
        setKlineStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value9(Date value) {
        setKlineEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value10(String value) {
        setSimilarRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value11(String value) {
        setRiseChance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value12(String value) {
        setMarketinfoJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value13(String value) {
        setExtParam(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value14(Integer value) {
        setSimilarUp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord value15(Integer value) {
        setSimilarDown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSimilarklineStockRecord values(Timestamp value1, Date value2, String value3, String value4, Short value5, String value6, String value7, Date value8, Date value9, String value10, String value11, String value12, String value13, Integer value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSimilarklineStockRecord
     */
    public TSimilarklineStockRecord() {
        super(TSimilarklineStock.T_SIMILARKLINE_STOCK);
    }

    /**
     * Create a detached, initialised TSimilarklineStockRecord
     */
    public TSimilarklineStockRecord(Timestamp releaseTime, Date tradeDate, String stockCode, String stockName, Short marketCode, String closelyStockCode, String closelyStockName, Date klineStartDate, Date klineEndDate, String similarRate, String riseChance, String marketinfoJson, String extParam, Integer similarUp, Integer similarDown) {
        super(TSimilarklineStock.T_SIMILARKLINE_STOCK);

        set(0, releaseTime);
        set(1, tradeDate);
        set(2, stockCode);
        set(3, stockName);
        set(4, marketCode);
        set(5, closelyStockCode);
        set(6, closelyStockName);
        set(7, klineStartDate);
        set(8, klineEndDate);
        set(9, similarRate);
        set(10, riseChance);
        set(11, marketinfoJson);
        set(12, extParam);
        set(13, similarUp);
        set(14, similarDown);
    }
}
