/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entry.mysql.tables.TStockmarketInfo;


/**
 * 股票市场信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TStockmarketInfoRecord extends UpdatableRecordImpl<TStockmarketInfoRecord> implements Record9<Timestamp, Date, String, String, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = -318840327;

    /**
     * Setter for <code>datasync.t_stockmarket_info.release_time</code>. 发布时间
     */
    public void setReleaseTime(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.release_time</code>. 发布时间
     */
    public Timestamp getReleaseTime() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.trade_date</code>. 交易日期
     */
    public void setTradeDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.trade_date</code>. 交易日期
     */
    public Date getTradeDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.ratio_sh</code>. 上证涨幅
     */
    public void setRatioSh(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.ratio_sh</code>. 上证涨幅
     */
    public String getRatioSh() {
        return (String) get(2);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.ratio_sz</code>. 深圳涨幅
     */
    public void setRatioSz(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.ratio_sz</code>. 深圳涨幅
     */
    public String getRatioSz() {
        return (String) get(3);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.ratio_sy</code>. 创业板涨幅
     */
    public void setRatioSy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.ratio_sy</code>. 创业板涨幅
     */
    public String getRatioSy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.total_up</code>. 上涨股票数
     */
    public void setTotalUp(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.total_up</code>. 上涨股票数
     */
    public Integer getTotalUp() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.total_down</code>. 下跌股票数
     */
    public void setTotalDown(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.total_down</code>. 下跌股票数
     */
    public Integer getTotalDown() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.comment</code>. 点评
     */
    public void setComment(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.comment</code>. 点评
     */
    public String getComment() {
        return (String) get(7);
    }

    /**
     * Setter for <code>datasync.t_stockmarket_info.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>datasync.t_stockmarket_info.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Date> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Timestamp, Date, String, String, String, Integer, Integer, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Timestamp, Date, String, String, String, Integer, Integer, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.RELEASE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.TRADE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.RATIO_SH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.RATIO_SZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.RATIO_SY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.TOTAL_UP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.TOTAL_DOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TStockmarketInfo.T_STOCKMARKET_INFO.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getTradeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRatioSh();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRatioSz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRatioSy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTotalUp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTotalDown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value1(Timestamp value) {
        setReleaseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value2(Date value) {
        setTradeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value3(String value) {
        setRatioSh(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value4(String value) {
        setRatioSz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value5(String value) {
        setRatioSy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value6(Integer value) {
        setTotalUp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value7(Integer value) {
        setTotalDown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value8(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord value9(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStockmarketInfoRecord values(Timestamp value1, Date value2, String value3, String value4, String value5, Integer value6, Integer value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TStockmarketInfoRecord
     */
    public TStockmarketInfoRecord() {
        super(TStockmarketInfo.T_STOCKMARKET_INFO);
    }

    /**
     * Create a detached, initialised TStockmarketInfoRecord
     */
    public TStockmarketInfoRecord(Timestamp releaseTime, Date tradeDate, String ratioSh, String ratioSz, String ratioSy, Integer totalUp, Integer totalDown, String comment, String remark) {
        super(TStockmarketInfo.T_STOCKMARKET_INFO);

        set(0, releaseTime);
        set(1, tradeDate);
        set(2, ratioSh);
        set(3, ratioSz);
        set(4, ratioSy);
        set(5, totalUp);
        set(6, totalDown);
        set(7, comment);
        set(8, remark);
    }
}
