/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import test.boot.entity.tables.TDatasource;
import test.boot.entity.tables.records.TDatasourceRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TDatasourceRecord, Integer> IDENTITY_T_DATASOURCE = Identities0.IDENTITY_T_DATASOURCE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TDatasourceRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TDatasourceRecord, Integer> IDENTITY_T_DATASOURCE = createIdentity(TDatasource.T_DATASOURCE, TDatasource.T_DATASOURCE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TDatasourceRecord> CONSTRAINT_6 = createUniqueKey(TDatasource.T_DATASOURCE, "CONSTRAINT_6", TDatasource.T_DATASOURCE.ID);
    }
}
