/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import test.boot.entity.tables.Datasource;
import test.boot.entity.tables.Template;
import test.boot.entity.tables.TemplateGroup;
import test.boot.entity.tables.TemplateGroupTemplate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1305341582;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.T_TEMPLATE_GROUP</code>.
     */
    public final TemplateGroup T_TEMPLATE_GROUP = test.boot.entity.tables.TemplateGroup.T_TEMPLATE_GROUP;

    /**
     * The table <code>PUBLIC.T_DATASOURCE</code>.
     */
    public final Datasource T_DATASOURCE = test.boot.entity.tables.Datasource.T_DATASOURCE;

    /**
     * The table <code>PUBLIC.T_TEMPLATE</code>.
     */
    public final Template T_TEMPLATE = test.boot.entity.tables.Template.T_TEMPLATE;

    /**
     * The table <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE</code>.
     */
    public final TemplateGroupTemplate R_TEMPLATE_GROUP_TEMPLATE = test.boot.entity.tables.TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_15C88540_4EC4_4257_AA2F_A2BC87F2F982,
            Sequences.SYSTEM_SEQUENCE_3EB0E551_10CF_4DBF_BB70_11DB80C681F9,
            Sequences.SYSTEM_SEQUENCE_3FABB1D1_1614_41BB_BB52_9131E25FD8DE,
            Sequences.SYSTEM_SEQUENCE_EAEC937E_F281_407C_92EF_D2648F19A07C);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TemplateGroup.T_TEMPLATE_GROUP,
            Datasource.T_DATASOURCE,
            Template.T_TEMPLATE,
            TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE);
    }
}
