/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_15C88540_4EC4_4257_AA2F_A2BC87F2F982</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_15C88540_4EC4_4257_AA2F_A2BC87F2F982 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_15C88540_4EC4_4257_AA2F_A2BC87F2F982", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_EAEC937E_F281_407C_92EF_D2648F19A07C</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_EAEC937E_F281_407C_92EF_D2648F19A07C = new SequenceImpl<Long>("SYSTEM_SEQUENCE_EAEC937E_F281_407C_92EF_D2648F19A07C", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
