/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import javax.annotation.Generated;

import test.boot.entity.tables.TDatasource;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.T_DATASOURCE</code>.
     */
    public static final TDatasource T_DATASOURCE = test.boot.entity.tables.TDatasource.T_DATASOURCE;
}
