/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import javax.annotation.Generated;

import test.boot.entity.tables.Datasource;
import test.boot.entity.tables.Template;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.T_DATASOURCE</code>.
     */
    public static final Datasource T_DATASOURCE = test.boot.entity.tables.Datasource.T_DATASOURCE;

    /**
     * The table <code>PUBLIC.T_TEMPLATE</code>.
     */
    public static final Template T_TEMPLATE = test.boot.entity.tables.Template.T_TEMPLATE;
}
