/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import test.boot.entry.mysql.tables.TAccountAsset;
import test.boot.entry.mysql.tables.TAccountMark;
import test.boot.entry.mysql.tables.TAccountMarkProdInfo;
import test.boot.entry.mysql.tables.TAccountMot;
import test.boot.entry.mysql.tables.TAccountProdInfo;
import test.boot.entry.mysql.tables.TDictLvl2;
import test.boot.entry.mysql.tables.TDictLvl2Desc;
import test.boot.entry.mysql.tables.TIndexHistperf;
import test.boot.entry.mysql.tables.TIndexSignal;
import test.boot.entry.mysql.tables.TProdAccountInfo;
import test.boot.entry.mysql.tables.TProdInfo;
import test.boot.entry.mysql.tables.TSimilarklineStock;
import test.boot.entry.mysql.tables.TStockmarketInfo;
import test.boot.entry.mysql.tables.TTopxStockinfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Datasync extends SchemaImpl {

    private static final long serialVersionUID = -572497866;

    /**
     * The reference instance of <code>datasync</code>
     */
    public static final Datasync DATASYNC = new Datasync();

    /**
     * The table <code>datasync.t_account_asset</code>.
     */
    public final TAccountAsset T_ACCOUNT_ASSET = test.boot.entry.mysql.tables.TAccountAsset.T_ACCOUNT_ASSET;

    /**
     * The table <code>datasync.t_account_mark</code>.
     */
    public final TAccountMark T_ACCOUNT_MARK = test.boot.entry.mysql.tables.TAccountMark.T_ACCOUNT_MARK;

    /**
     * The table <code>datasync.t_account_mark_prod_info</code>.
     */
    public final TAccountMarkProdInfo T_ACCOUNT_MARK_PROD_INFO = test.boot.entry.mysql.tables.TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO;

    /**
     * The table <code>datasync.t_account_mot</code>.
     */
    public final TAccountMot T_ACCOUNT_MOT = test.boot.entry.mysql.tables.TAccountMot.T_ACCOUNT_MOT;

    /**
     * The table <code>datasync.t_account_prod_info</code>.
     */
    public final TAccountProdInfo T_ACCOUNT_PROD_INFO = test.boot.entry.mysql.tables.TAccountProdInfo.T_ACCOUNT_PROD_INFO;

    /**
     * 二级数据字典
     */
    public final TDictLvl2 T_DICT_LVL2 = test.boot.entry.mysql.tables.TDictLvl2.T_DICT_LVL2;

    /**
     * 二级数据字典描述
     */
    public final TDictLvl2Desc T_DICT_LVL2_DESC = test.boot.entry.mysql.tables.TDictLvl2Desc.T_DICT_LVL2_DESC;

    /**
     * 历史预警后大盘指数表现信息
     */
    public final TIndexHistperf T_INDEX_HISTPERF = test.boot.entry.mysql.tables.TIndexHistperf.T_INDEX_HISTPERF;

    /**
     * 指数信号信息
     */
    public final TIndexSignal T_INDEX_SIGNAL = test.boot.entry.mysql.tables.TIndexSignal.T_INDEX_SIGNAL;

    /**
     * The table <code>datasync.t_prod_account_info</code>.
     */
    public final TProdAccountInfo T_PROD_ACCOUNT_INFO = test.boot.entry.mysql.tables.TProdAccountInfo.T_PROD_ACCOUNT_INFO;

    /**
     * The table <code>datasync.t_prod_info</code>.
     */
    public final TProdInfo T_PROD_INFO = test.boot.entry.mysql.tables.TProdInfo.T_PROD_INFO;

    /**
     * 相似k线股票信息
     */
    public final TSimilarklineStock T_SIMILARKLINE_STOCK = test.boot.entry.mysql.tables.TSimilarklineStock.T_SIMILARKLINE_STOCK;

    /**
     * 股票市场信息
     */
    public final TStockmarketInfo T_STOCKMARKET_INFO = test.boot.entry.mysql.tables.TStockmarketInfo.T_STOCKMARKET_INFO;

    /**
     * topx股票信息
     */
    public final TTopxStockinfo T_TOPX_STOCKINFO = test.boot.entry.mysql.tables.TTopxStockinfo.T_TOPX_STOCKINFO;

    /**
     * No further instances allowed
     */
    private Datasync() {
        super("datasync", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TAccountAsset.T_ACCOUNT_ASSET,
            TAccountMark.T_ACCOUNT_MARK,
            TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO,
            TAccountMot.T_ACCOUNT_MOT,
            TAccountProdInfo.T_ACCOUNT_PROD_INFO,
            TDictLvl2.T_DICT_LVL2,
            TDictLvl2Desc.T_DICT_LVL2_DESC,
            TIndexHistperf.T_INDEX_HISTPERF,
            TIndexSignal.T_INDEX_SIGNAL,
            TProdAccountInfo.T_PROD_ACCOUNT_INFO,
            TProdInfo.T_PROD_INFO,
            TSimilarklineStock.T_SIMILARKLINE_STOCK,
            TStockmarketInfo.T_STOCKMARKET_INFO,
            TTopxStockinfo.T_TOPX_STOCKINFO);
    }
}
