/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql;


import javax.annotation.Generated;

import test.boot.entry.mysql.tables.TAccountAsset;
import test.boot.entry.mysql.tables.TAccountMark;
import test.boot.entry.mysql.tables.TAccountMarkProdInfo;
import test.boot.entry.mysql.tables.TAccountMot;
import test.boot.entry.mysql.tables.TAccountProdInfo;
import test.boot.entry.mysql.tables.TDictLvl2;
import test.boot.entry.mysql.tables.TDictLvl2Desc;
import test.boot.entry.mysql.tables.TIndexHistperf;
import test.boot.entry.mysql.tables.TIndexSignal;
import test.boot.entry.mysql.tables.TProdAccountInfo;
import test.boot.entry.mysql.tables.TProdInfo;
import test.boot.entry.mysql.tables.TSimilarklineStock;
import test.boot.entry.mysql.tables.TStockmarketInfo;
import test.boot.entry.mysql.tables.TTopxStockinfo;


/**
 * Convenience access to all tables in datasync
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>datasync.t_account_asset</code>.
     */
    public static final TAccountAsset T_ACCOUNT_ASSET = test.boot.entry.mysql.tables.TAccountAsset.T_ACCOUNT_ASSET;

    /**
     * The table <code>datasync.t_account_mark</code>.
     */
    public static final TAccountMark T_ACCOUNT_MARK = test.boot.entry.mysql.tables.TAccountMark.T_ACCOUNT_MARK;

    /**
     * The table <code>datasync.t_account_mark_prod_info</code>.
     */
    public static final TAccountMarkProdInfo T_ACCOUNT_MARK_PROD_INFO = test.boot.entry.mysql.tables.TAccountMarkProdInfo.T_ACCOUNT_MARK_PROD_INFO;

    /**
     * The table <code>datasync.t_account_mot</code>.
     */
    public static final TAccountMot T_ACCOUNT_MOT = test.boot.entry.mysql.tables.TAccountMot.T_ACCOUNT_MOT;

    /**
     * The table <code>datasync.t_account_prod_info</code>.
     */
    public static final TAccountProdInfo T_ACCOUNT_PROD_INFO = test.boot.entry.mysql.tables.TAccountProdInfo.T_ACCOUNT_PROD_INFO;

    /**
     * 二级数据字典
     */
    public static final TDictLvl2 T_DICT_LVL2 = test.boot.entry.mysql.tables.TDictLvl2.T_DICT_LVL2;

    /**
     * 二级数据字典描述
     */
    public static final TDictLvl2Desc T_DICT_LVL2_DESC = test.boot.entry.mysql.tables.TDictLvl2Desc.T_DICT_LVL2_DESC;

    /**
     * 历史预警后大盘指数表现信息
     */
    public static final TIndexHistperf T_INDEX_HISTPERF = test.boot.entry.mysql.tables.TIndexHistperf.T_INDEX_HISTPERF;

    /**
     * 指数信号信息
     */
    public static final TIndexSignal T_INDEX_SIGNAL = test.boot.entry.mysql.tables.TIndexSignal.T_INDEX_SIGNAL;

    /**
     * The table <code>datasync.t_prod_account_info</code>.
     */
    public static final TProdAccountInfo T_PROD_ACCOUNT_INFO = test.boot.entry.mysql.tables.TProdAccountInfo.T_PROD_ACCOUNT_INFO;

    /**
     * The table <code>datasync.t_prod_info</code>.
     */
    public static final TProdInfo T_PROD_INFO = test.boot.entry.mysql.tables.TProdInfo.T_PROD_INFO;

    /**
     * 相似k线股票信息
     */
    public static final TSimilarklineStock T_SIMILARKLINE_STOCK = test.boot.entry.mysql.tables.TSimilarklineStock.T_SIMILARKLINE_STOCK;

    /**
     * 股票市场信息
     */
    public static final TStockmarketInfo T_STOCKMARKET_INFO = test.boot.entry.mysql.tables.TStockmarketInfo.T_STOCKMARKET_INFO;

    /**
     * topx股票信息
     */
    public static final TTopxStockinfo T_TOPX_STOCKINFO = test.boot.entry.mysql.tables.TTopxStockinfo.T_TOPX_STOCKINFO;
}
