/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entity.tables.TemplateGroupTemplate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateGroupTemplateRecord extends UpdatableRecordImpl<TemplateGroupTemplateRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1217655353;

    /**
     * Setter for <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.TG_ID</code>.
     */
    public void setTgId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.TG_ID</code>.
     */
    public Integer getTgId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.T_ID</code>.
     */
    public void setTId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.R_TEMPLATE_GROUP_TEMPLATE.T_ID</code>.
     */
    public Integer getTId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE.TG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE.T_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateGroupTemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateGroupTemplateRecord value2(Integer value) {
        setTgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateGroupTemplateRecord value3(Integer value) {
        setTId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateGroupTemplateRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateGroupTemplateRecord
     */
    public TemplateGroupTemplateRecord() {
        super(TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE);
    }

    /**
     * Create a detached, initialised TemplateGroupTemplateRecord
     */
    public TemplateGroupTemplateRecord(Integer id, Integer tgId, Integer tId) {
        super(TemplateGroupTemplate.R_TEMPLATE_GROUP_TEMPLATE);

        set(0, id);
        set(1, tgId);
        set(2, tId);
    }
}
