/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entity.tables.Template;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateRecord extends UpdatableRecordImpl<TemplateRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1748793163;

    /**
     * Setter for <code>PUBLIC.T_TEMPLATE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.T_TEMPLATE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.T_TEMPLATE.CONTENT</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.T_TEMPLATE.CONTENT</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.T_TEMPLATE.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.T_TEMPLATE.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.T_TEMPLATE.FILE_NAME</code>.
     */
    public void setFileName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.T_TEMPLATE.FILE_NAME</code>.
     */
    public String getFileName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.T_TEMPLATE.FILE_PATH</code>.
     */
    public void setFilePath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.T_TEMPLATE.FILE_PATH</code>.
     */
    public String getFilePath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.T_TEMPLATE.PARAMETERS</code>.
     */
    public void setParameters(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.T_TEMPLATE.PARAMETERS</code>.
     */
    public String getParameters() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Template.T_TEMPLATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Template.T_TEMPLATE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Template.T_TEMPLATE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Template.T_TEMPLATE.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Template.T_TEMPLATE.FILE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Template.T_TEMPLATE.PARAMETERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getParameters();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value4(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value5(String value) {
        setFilePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value6(String value) {
        setParameters(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateRecord
     */
    public TemplateRecord() {
        super(Template.T_TEMPLATE);
    }

    /**
     * Create a detached, initialised TemplateRecord
     */
    public TemplateRecord(Integer id, String content, String name, String fileName, String filePath, String parameters) {
        super(Template.T_TEMPLATE);

        set(0, id);
        set(1, content);
        set(2, name);
        set(3, fileName);
        set(4, filePath);
        set(5, parameters);
    }
}
