/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountProdInfo implements Serializable {

    private static final long serialVersionUID = -1511938953;

    private String     fundAccount;
    private String     prodCode;
    private String     orgId;
    private BigDecimal interAsset;
    private BigDecimal outerAsset;
    private BigDecimal totalAsset;
    private BigDecimal matchRatio;
    private BigDecimal last_12YieldRatio;
    private BigDecimal minMark;
    private BigDecimal stressMark;
    private BigDecimal historyMark;
    private Integer    holdStatus;
    private BigDecimal buyAble;
    private Timestamp  updateTime;

    public TAccountProdInfo() {}

    public TAccountProdInfo(TAccountProdInfo value) {
        this.fundAccount = value.fundAccount;
        this.prodCode = value.prodCode;
        this.orgId = value.orgId;
        this.interAsset = value.interAsset;
        this.outerAsset = value.outerAsset;
        this.totalAsset = value.totalAsset;
        this.matchRatio = value.matchRatio;
        this.last_12YieldRatio = value.last_12YieldRatio;
        this.minMark = value.minMark;
        this.stressMark = value.stressMark;
        this.historyMark = value.historyMark;
        this.holdStatus = value.holdStatus;
        this.buyAble = value.buyAble;
        this.updateTime = value.updateTime;
    }

    public TAccountProdInfo(
        String     fundAccount,
        String     prodCode,
        String     orgId,
        BigDecimal interAsset,
        BigDecimal outerAsset,
        BigDecimal totalAsset,
        BigDecimal matchRatio,
        BigDecimal last_12YieldRatio,
        BigDecimal minMark,
        BigDecimal stressMark,
        BigDecimal historyMark,
        Integer    holdStatus,
        BigDecimal buyAble,
        Timestamp  updateTime
    ) {
        this.fundAccount = fundAccount;
        this.prodCode = prodCode;
        this.orgId = orgId;
        this.interAsset = interAsset;
        this.outerAsset = outerAsset;
        this.totalAsset = totalAsset;
        this.matchRatio = matchRatio;
        this.last_12YieldRatio = last_12YieldRatio;
        this.minMark = minMark;
        this.stressMark = stressMark;
        this.historyMark = historyMark;
        this.holdStatus = holdStatus;
        this.buyAble = buyAble;
        this.updateTime = updateTime;
    }

    public String getFundAccount() {
        return this.fundAccount;
    }

    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount;
    }

    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public BigDecimal getInterAsset() {
        return this.interAsset;
    }

    public void setInterAsset(BigDecimal interAsset) {
        this.interAsset = interAsset;
    }

    public BigDecimal getOuterAsset() {
        return this.outerAsset;
    }

    public void setOuterAsset(BigDecimal outerAsset) {
        this.outerAsset = outerAsset;
    }

    public BigDecimal getTotalAsset() {
        return this.totalAsset;
    }

    public void setTotalAsset(BigDecimal totalAsset) {
        this.totalAsset = totalAsset;
    }

    public BigDecimal getMatchRatio() {
        return this.matchRatio;
    }

    public void setMatchRatio(BigDecimal matchRatio) {
        this.matchRatio = matchRatio;
    }

    public BigDecimal getLast_12YieldRatio() {
        return this.last_12YieldRatio;
    }

    public void setLast_12YieldRatio(BigDecimal last_12YieldRatio) {
        this.last_12YieldRatio = last_12YieldRatio;
    }

    public BigDecimal getMinMark() {
        return this.minMark;
    }

    public void setMinMark(BigDecimal minMark) {
        this.minMark = minMark;
    }

    public BigDecimal getStressMark() {
        return this.stressMark;
    }

    public void setStressMark(BigDecimal stressMark) {
        this.stressMark = stressMark;
    }

    public BigDecimal getHistoryMark() {
        return this.historyMark;
    }

    public void setHistoryMark(BigDecimal historyMark) {
        this.historyMark = historyMark;
    }

    public Integer getHoldStatus() {
        return this.holdStatus;
    }

    public void setHoldStatus(Integer holdStatus) {
        this.holdStatus = holdStatus;
    }

    public BigDecimal getBuyAble() {
        return this.buyAble;
    }

    public void setBuyAble(BigDecimal buyAble) {
        this.buyAble = buyAble;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountProdInfo (");

        sb.append(fundAccount);
        sb.append(", ").append(prodCode);
        sb.append(", ").append(orgId);
        sb.append(", ").append(interAsset);
        sb.append(", ").append(outerAsset);
        sb.append(", ").append(totalAsset);
        sb.append(", ").append(matchRatio);
        sb.append(", ").append(last_12YieldRatio);
        sb.append(", ").append(minMark);
        sb.append(", ").append(stressMark);
        sb.append(", ").append(historyMark);
        sb.append(", ").append(holdStatus);
        sb.append(", ").append(buyAble);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
