/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMot implements Serializable {

    private static final long serialVersionUID = 150724204;

    private String     fundAccount;
    private String     motMark;
    private BigDecimal motLevel;
    private String     motExtend;
    private Timestamp  updateTime;

    public TAccountMot() {}

    public TAccountMot(TAccountMot value) {
        this.fundAccount = value.fundAccount;
        this.motMark = value.motMark;
        this.motLevel = value.motLevel;
        this.motExtend = value.motExtend;
        this.updateTime = value.updateTime;
    }

    public TAccountMot(
        String     fundAccount,
        String     motMark,
        BigDecimal motLevel,
        String     motExtend,
        Timestamp  updateTime
    ) {
        this.fundAccount = fundAccount;
        this.motMark = motMark;
        this.motLevel = motLevel;
        this.motExtend = motExtend;
        this.updateTime = updateTime;
    }

    public String getFundAccount() {
        return this.fundAccount;
    }

    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount;
    }

    public String getMotMark() {
        return this.motMark;
    }

    public void setMotMark(String motMark) {
        this.motMark = motMark;
    }

    public BigDecimal getMotLevel() {
        return this.motLevel;
    }

    public void setMotLevel(BigDecimal motLevel) {
        this.motLevel = motLevel;
    }

    public String getMotExtend() {
        return this.motExtend;
    }

    public void setMotExtend(String motExtend) {
        this.motExtend = motExtend;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountMot (");

        sb.append(fundAccount);
        sb.append(", ").append(motMark);
        sb.append(", ").append(motLevel);
        sb.append(", ").append(motExtend);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
