/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMark implements Serializable {

    private static final long serialVersionUID = 2145808734;

    private String    fundAccount;
    private UInteger  markType;
    private UInteger  markValue;
    private Timestamp updateTime;

    public TAccountMark() {}

    public TAccountMark(TAccountMark value) {
        this.fundAccount = value.fundAccount;
        this.markType = value.markType;
        this.markValue = value.markValue;
        this.updateTime = value.updateTime;
    }

    public TAccountMark(
        String    fundAccount,
        UInteger  markType,
        UInteger  markValue,
        Timestamp updateTime
    ) {
        this.fundAccount = fundAccount;
        this.markType = markType;
        this.markValue = markValue;
        this.updateTime = updateTime;
    }

    public String getFundAccount() {
        return this.fundAccount;
    }

    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount;
    }

    public UInteger getMarkType() {
        return this.markType;
    }

    public void setMarkType(UInteger markType) {
        this.markType = markType;
    }

    public UInteger getMarkValue() {
        return this.markValue;
    }

    public void setMarkValue(UInteger markValue) {
        this.markValue = markValue;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountMark (");

        sb.append(fundAccount);
        sb.append(", ").append(markType);
        sb.append(", ").append(markValue);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
