/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountMarkProdInfo implements Serializable {

    private static final long serialVersionUID = 1535328499;

    private UInteger  prodType;
    private String    prodCode;
    private Timestamp updateTime;
    private String    prodCategory;

    public TAccountMarkProdInfo() {}

    public TAccountMarkProdInfo(TAccountMarkProdInfo value) {
        this.prodType = value.prodType;
        this.prodCode = value.prodCode;
        this.updateTime = value.updateTime;
        this.prodCategory = value.prodCategory;
    }

    public TAccountMarkProdInfo(
        UInteger  prodType,
        String    prodCode,
        Timestamp updateTime,
        String    prodCategory
    ) {
        this.prodType = prodType;
        this.prodCode = prodCode;
        this.updateTime = updateTime;
        this.prodCategory = prodCategory;
    }

    public UInteger getProdType() {
        return this.prodType;
    }

    public void setProdType(UInteger prodType) {
        this.prodType = prodType;
    }

    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public String getProdCategory() {
        return this.prodCategory;
    }

    public void setProdCategory(String prodCategory) {
        this.prodCategory = prodCategory;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountMarkProdInfo (");

        sb.append(prodType);
        sb.append(", ").append(prodCode);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(prodCategory);

        sb.append(")");
        return sb.toString();
    }
}
