/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountAsset implements Serializable {

    private static final long serialVersionUID = -851668138;

    private String     fundAccount;
    private String     orgId;
    private BigDecimal interAsset;
    private BigDecimal outerAsset;
    private BigDecimal totalAsset;
    private BigDecimal expireAsset;
    private Timestamp  updateTime;

    public TAccountAsset() {}

    public TAccountAsset(TAccountAsset value) {
        this.fundAccount = value.fundAccount;
        this.orgId = value.orgId;
        this.interAsset = value.interAsset;
        this.outerAsset = value.outerAsset;
        this.totalAsset = value.totalAsset;
        this.expireAsset = value.expireAsset;
        this.updateTime = value.updateTime;
    }

    public TAccountAsset(
        String     fundAccount,
        String     orgId,
        BigDecimal interAsset,
        BigDecimal outerAsset,
        BigDecimal totalAsset,
        BigDecimal expireAsset,
        Timestamp  updateTime
    ) {
        this.fundAccount = fundAccount;
        this.orgId = orgId;
        this.interAsset = interAsset;
        this.outerAsset = outerAsset;
        this.totalAsset = totalAsset;
        this.expireAsset = expireAsset;
        this.updateTime = updateTime;
    }

    public String getFundAccount() {
        return this.fundAccount;
    }

    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public BigDecimal getInterAsset() {
        return this.interAsset;
    }

    public void setInterAsset(BigDecimal interAsset) {
        this.interAsset = interAsset;
    }

    public BigDecimal getOuterAsset() {
        return this.outerAsset;
    }

    public void setOuterAsset(BigDecimal outerAsset) {
        this.outerAsset = outerAsset;
    }

    public BigDecimal getTotalAsset() {
        return this.totalAsset;
    }

    public void setTotalAsset(BigDecimal totalAsset) {
        this.totalAsset = totalAsset;
    }

    public BigDecimal getExpireAsset() {
        return this.expireAsset;
    }

    public void setExpireAsset(BigDecimal expireAsset) {
        this.expireAsset = expireAsset;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountAsset (");

        sb.append(fundAccount);
        sb.append(", ").append(orgId);
        sb.append(", ").append(interAsset);
        sb.append(", ").append(outerAsset);
        sb.append(", ").append(totalAsset);
        sb.append(", ").append(expireAsset);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
