/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 二级数据字典
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDictLvl2 implements Serializable {

    private static final long serialVersionUID = 1230349751;

    private String    dictItem;
    private String    dictKey;
    private String    dictValue;
    private Timestamp updateTime;
    private Timestamp createTime;

    public TDictLvl2() {}

    public TDictLvl2(TDictLvl2 value) {
        this.dictItem = value.dictItem;
        this.dictKey = value.dictKey;
        this.dictValue = value.dictValue;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public TDictLvl2(
        String    dictItem,
        String    dictKey,
        String    dictValue,
        Timestamp updateTime,
        Timestamp createTime
    ) {
        this.dictItem = dictItem;
        this.dictKey = dictKey;
        this.dictValue = dictValue;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public String getDictItem() {
        return this.dictItem;
    }

    public void setDictItem(String dictItem) {
        this.dictItem = dictItem;
    }

    public String getDictKey() {
        return this.dictKey;
    }

    public void setDictKey(String dictKey) {
        this.dictKey = dictKey;
    }

    public String getDictValue() {
        return this.dictValue;
    }

    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDictLvl2 (");

        sb.append(dictItem);
        sb.append(", ").append(dictKey);
        sb.append(", ").append(dictValue);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
