/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 历史预警后大盘指数表现信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndexHistperf implements Serializable {

    private static final long serialVersionUID = -1034961653;

    private Timestamp releaseTime;
    private Date      tradeDate;
    private String    indexCode;
    private String    indexName;
    private String    closePriceBefore;
    private String    closePriceAfter;
    private String    netRatio;
    private String    ratio;
    private String    remark;

    public TIndexHistperf() {}

    public TIndexHistperf(TIndexHistperf value) {
        this.releaseTime = value.releaseTime;
        this.tradeDate = value.tradeDate;
        this.indexCode = value.indexCode;
        this.indexName = value.indexName;
        this.closePriceBefore = value.closePriceBefore;
        this.closePriceAfter = value.closePriceAfter;
        this.netRatio = value.netRatio;
        this.ratio = value.ratio;
        this.remark = value.remark;
    }

    public TIndexHistperf(
        Timestamp releaseTime,
        Date      tradeDate,
        String    indexCode,
        String    indexName,
        String    closePriceBefore,
        String    closePriceAfter,
        String    netRatio,
        String    ratio,
        String    remark
    ) {
        this.releaseTime = releaseTime;
        this.tradeDate = tradeDate;
        this.indexCode = indexCode;
        this.indexName = indexName;
        this.closePriceBefore = closePriceBefore;
        this.closePriceAfter = closePriceAfter;
        this.netRatio = netRatio;
        this.ratio = ratio;
        this.remark = remark;
    }

    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    public Date getTradeDate() {
        return this.tradeDate;
    }

    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    public String getIndexCode() {
        return this.indexCode;
    }

    public void setIndexCode(String indexCode) {
        this.indexCode = indexCode;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    public String getClosePriceBefore() {
        return this.closePriceBefore;
    }

    public void setClosePriceBefore(String closePriceBefore) {
        this.closePriceBefore = closePriceBefore;
    }

    public String getClosePriceAfter() {
        return this.closePriceAfter;
    }

    public void setClosePriceAfter(String closePriceAfter) {
        this.closePriceAfter = closePriceAfter;
    }

    public String getNetRatio() {
        return this.netRatio;
    }

    public void setNetRatio(String netRatio) {
        this.netRatio = netRatio;
    }

    public String getRatio() {
        return this.ratio;
    }

    public void setRatio(String ratio) {
        this.ratio = ratio;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TIndexHistperf (");

        sb.append(releaseTime);
        sb.append(", ").append(tradeDate);
        sb.append(", ").append(indexCode);
        sb.append(", ").append(indexName);
        sb.append(", ").append(closePriceBefore);
        sb.append(", ").append(closePriceAfter);
        sb.append(", ").append(netRatio);
        sb.append(", ").append(ratio);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
