/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 指数信号信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TIndexSignal implements Serializable {

    private static final long serialVersionUID = -639782589;

    private Timestamp releaseTime;
    private Date      tradeDate;
    private String    signal;
    private Short     signalType;
    private String    comment;
    private String    remark;

    public TIndexSignal() {}

    public TIndexSignal(TIndexSignal value) {
        this.releaseTime = value.releaseTime;
        this.tradeDate = value.tradeDate;
        this.signal = value.signal;
        this.signalType = value.signalType;
        this.comment = value.comment;
        this.remark = value.remark;
    }

    public TIndexSignal(
        Timestamp releaseTime,
        Date      tradeDate,
        String    signal,
        Short     signalType,
        String    comment,
        String    remark
    ) {
        this.releaseTime = releaseTime;
        this.tradeDate = tradeDate;
        this.signal = signal;
        this.signalType = signalType;
        this.comment = comment;
        this.remark = remark;
    }

    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    public Date getTradeDate() {
        return this.tradeDate;
    }

    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    public String getSignal() {
        return this.signal;
    }

    public void setSignal(String signal) {
        this.signal = signal;
    }

    public Short getSignalType() {
        return this.signalType;
    }

    public void setSignalType(Short signalType) {
        this.signalType = signalType;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TIndexSignal (");

        sb.append(releaseTime);
        sb.append(", ").append(tradeDate);
        sb.append(", ").append(signal);
        sb.append(", ").append(signalType);
        sb.append(", ").append(comment);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
