/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProdAccountInfo implements Serializable {

    private static final long serialVersionUID = 1831329399;

    private String     prodCode;
    private String     fundAccount;
    private BigDecimal matchRatio;
    private BigDecimal interAsset;
    private BigDecimal outerAsset;
    private BigDecimal totalAsset;
    private BigDecimal totalAssetMark;
    private BigDecimal expireAsset;
    private BigDecimal expireAssetMark;
    private BigDecimal historyMark;
    private BigDecimal last_12YieldRatio;
    private BigDecimal yieldMark;
    private BigDecimal stockTurnRatio;
    private BigDecimal stockTurnRatioMark;
    private BigDecimal buyAble;
    private Timestamp  updateTime;
    private String     orgId;
    private UInteger   holdStatus;

    public TProdAccountInfo() {}

    public TProdAccountInfo(TProdAccountInfo value) {
        this.prodCode = value.prodCode;
        this.fundAccount = value.fundAccount;
        this.matchRatio = value.matchRatio;
        this.interAsset = value.interAsset;
        this.outerAsset = value.outerAsset;
        this.totalAsset = value.totalAsset;
        this.totalAssetMark = value.totalAssetMark;
        this.expireAsset = value.expireAsset;
        this.expireAssetMark = value.expireAssetMark;
        this.historyMark = value.historyMark;
        this.last_12YieldRatio = value.last_12YieldRatio;
        this.yieldMark = value.yieldMark;
        this.stockTurnRatio = value.stockTurnRatio;
        this.stockTurnRatioMark = value.stockTurnRatioMark;
        this.buyAble = value.buyAble;
        this.updateTime = value.updateTime;
        this.orgId = value.orgId;
        this.holdStatus = value.holdStatus;
    }

    public TProdAccountInfo(
        String     prodCode,
        String     fundAccount,
        BigDecimal matchRatio,
        BigDecimal interAsset,
        BigDecimal outerAsset,
        BigDecimal totalAsset,
        BigDecimal totalAssetMark,
        BigDecimal expireAsset,
        BigDecimal expireAssetMark,
        BigDecimal historyMark,
        BigDecimal last_12YieldRatio,
        BigDecimal yieldMark,
        BigDecimal stockTurnRatio,
        BigDecimal stockTurnRatioMark,
        BigDecimal buyAble,
        Timestamp  updateTime,
        String     orgId,
        UInteger   holdStatus
    ) {
        this.prodCode = prodCode;
        this.fundAccount = fundAccount;
        this.matchRatio = matchRatio;
        this.interAsset = interAsset;
        this.outerAsset = outerAsset;
        this.totalAsset = totalAsset;
        this.totalAssetMark = totalAssetMark;
        this.expireAsset = expireAsset;
        this.expireAssetMark = expireAssetMark;
        this.historyMark = historyMark;
        this.last_12YieldRatio = last_12YieldRatio;
        this.yieldMark = yieldMark;
        this.stockTurnRatio = stockTurnRatio;
        this.stockTurnRatioMark = stockTurnRatioMark;
        this.buyAble = buyAble;
        this.updateTime = updateTime;
        this.orgId = orgId;
        this.holdStatus = holdStatus;
    }

    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    public String getFundAccount() {
        return this.fundAccount;
    }

    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount;
    }

    public BigDecimal getMatchRatio() {
        return this.matchRatio;
    }

    public void setMatchRatio(BigDecimal matchRatio) {
        this.matchRatio = matchRatio;
    }

    public BigDecimal getInterAsset() {
        return this.interAsset;
    }

    public void setInterAsset(BigDecimal interAsset) {
        this.interAsset = interAsset;
    }

    public BigDecimal getOuterAsset() {
        return this.outerAsset;
    }

    public void setOuterAsset(BigDecimal outerAsset) {
        this.outerAsset = outerAsset;
    }

    public BigDecimal getTotalAsset() {
        return this.totalAsset;
    }

    public void setTotalAsset(BigDecimal totalAsset) {
        this.totalAsset = totalAsset;
    }

    public BigDecimal getTotalAssetMark() {
        return this.totalAssetMark;
    }

    public void setTotalAssetMark(BigDecimal totalAssetMark) {
        this.totalAssetMark = totalAssetMark;
    }

    public BigDecimal getExpireAsset() {
        return this.expireAsset;
    }

    public void setExpireAsset(BigDecimal expireAsset) {
        this.expireAsset = expireAsset;
    }

    public BigDecimal getExpireAssetMark() {
        return this.expireAssetMark;
    }

    public void setExpireAssetMark(BigDecimal expireAssetMark) {
        this.expireAssetMark = expireAssetMark;
    }

    public BigDecimal getHistoryMark() {
        return this.historyMark;
    }

    public void setHistoryMark(BigDecimal historyMark) {
        this.historyMark = historyMark;
    }

    public BigDecimal getLast_12YieldRatio() {
        return this.last_12YieldRatio;
    }

    public void setLast_12YieldRatio(BigDecimal last_12YieldRatio) {
        this.last_12YieldRatio = last_12YieldRatio;
    }

    public BigDecimal getYieldMark() {
        return this.yieldMark;
    }

    public void setYieldMark(BigDecimal yieldMark) {
        this.yieldMark = yieldMark;
    }

    public BigDecimal getStockTurnRatio() {
        return this.stockTurnRatio;
    }

    public void setStockTurnRatio(BigDecimal stockTurnRatio) {
        this.stockTurnRatio = stockTurnRatio;
    }

    public BigDecimal getStockTurnRatioMark() {
        return this.stockTurnRatioMark;
    }

    public void setStockTurnRatioMark(BigDecimal stockTurnRatioMark) {
        this.stockTurnRatioMark = stockTurnRatioMark;
    }

    public BigDecimal getBuyAble() {
        return this.buyAble;
    }

    public void setBuyAble(BigDecimal buyAble) {
        this.buyAble = buyAble;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public UInteger getHoldStatus() {
        return this.holdStatus;
    }

    public void setHoldStatus(UInteger holdStatus) {
        this.holdStatus = holdStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TProdAccountInfo (");

        sb.append(prodCode);
        sb.append(", ").append(fundAccount);
        sb.append(", ").append(matchRatio);
        sb.append(", ").append(interAsset);
        sb.append(", ").append(outerAsset);
        sb.append(", ").append(totalAsset);
        sb.append(", ").append(totalAssetMark);
        sb.append(", ").append(expireAsset);
        sb.append(", ").append(expireAssetMark);
        sb.append(", ").append(historyMark);
        sb.append(", ").append(last_12YieldRatio);
        sb.append(", ").append(yieldMark);
        sb.append(", ").append(stockTurnRatio);
        sb.append(", ").append(stockTurnRatioMark);
        sb.append(", ").append(buyAble);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(orgId);
        sb.append(", ").append(holdStatus);

        sb.append(")");
        return sb.toString();
    }
}
