/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProdInfo implements Serializable {

    private static final long serialVersionUID = -1738484820;

    private String    prodCode;
    private Timestamp updateTime;

    public TProdInfo() {}

    public TProdInfo(TProdInfo value) {
        this.prodCode = value.prodCode;
        this.updateTime = value.updateTime;
    }

    public TProdInfo(
        String    prodCode,
        Timestamp updateTime
    ) {
        this.prodCode = prodCode;
        this.updateTime = updateTime;
    }

    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TProdInfo (");

        sb.append(prodCode);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
