/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 相似k线股票信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSimilarklineStock implements Serializable {

    private static final long serialVersionUID = -498237501;

    private Timestamp releaseTime;
    private Date      tradeDate;
    private String    stockCode;
    private String    stockName;
    private Short     marketCode;
    private String    closelyStockCode;
    private String    closelyStockName;
    private Date      klineStartDate;
    private Date      klineEndDate;
    private String    similarRate;
    private String    riseChance;
    private String    marketinfoJson;
    private String    extParam;
    private Integer   similarUp;
    private Integer   similarDown;

    public TSimilarklineStock() {}

    public TSimilarklineStock(TSimilarklineStock value) {
        this.releaseTime = value.releaseTime;
        this.tradeDate = value.tradeDate;
        this.stockCode = value.stockCode;
        this.stockName = value.stockName;
        this.marketCode = value.marketCode;
        this.closelyStockCode = value.closelyStockCode;
        this.closelyStockName = value.closelyStockName;
        this.klineStartDate = value.klineStartDate;
        this.klineEndDate = value.klineEndDate;
        this.similarRate = value.similarRate;
        this.riseChance = value.riseChance;
        this.marketinfoJson = value.marketinfoJson;
        this.extParam = value.extParam;
        this.similarUp = value.similarUp;
        this.similarDown = value.similarDown;
    }

    public TSimilarklineStock(
        Timestamp releaseTime,
        Date      tradeDate,
        String    stockCode,
        String    stockName,
        Short     marketCode,
        String    closelyStockCode,
        String    closelyStockName,
        Date      klineStartDate,
        Date      klineEndDate,
        String    similarRate,
        String    riseChance,
        String    marketinfoJson,
        String    extParam,
        Integer   similarUp,
        Integer   similarDown
    ) {
        this.releaseTime = releaseTime;
        this.tradeDate = tradeDate;
        this.stockCode = stockCode;
        this.stockName = stockName;
        this.marketCode = marketCode;
        this.closelyStockCode = closelyStockCode;
        this.closelyStockName = closelyStockName;
        this.klineStartDate = klineStartDate;
        this.klineEndDate = klineEndDate;
        this.similarRate = similarRate;
        this.riseChance = riseChance;
        this.marketinfoJson = marketinfoJson;
        this.extParam = extParam;
        this.similarUp = similarUp;
        this.similarDown = similarDown;
    }

    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    public Date getTradeDate() {
        return this.tradeDate;
    }

    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    public String getStockCode() {
        return this.stockCode;
    }

    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    public String getStockName() {
        return this.stockName;
    }

    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    public Short getMarketCode() {
        return this.marketCode;
    }

    public void setMarketCode(Short marketCode) {
        this.marketCode = marketCode;
    }

    public String getCloselyStockCode() {
        return this.closelyStockCode;
    }

    public void setCloselyStockCode(String closelyStockCode) {
        this.closelyStockCode = closelyStockCode;
    }

    public String getCloselyStockName() {
        return this.closelyStockName;
    }

    public void setCloselyStockName(String closelyStockName) {
        this.closelyStockName = closelyStockName;
    }

    public Date getKlineStartDate() {
        return this.klineStartDate;
    }

    public void setKlineStartDate(Date klineStartDate) {
        this.klineStartDate = klineStartDate;
    }

    public Date getKlineEndDate() {
        return this.klineEndDate;
    }

    public void setKlineEndDate(Date klineEndDate) {
        this.klineEndDate = klineEndDate;
    }

    public String getSimilarRate() {
        return this.similarRate;
    }

    public void setSimilarRate(String similarRate) {
        this.similarRate = similarRate;
    }

    public String getRiseChance() {
        return this.riseChance;
    }

    public void setRiseChance(String riseChance) {
        this.riseChance = riseChance;
    }

    public String getMarketinfoJson() {
        return this.marketinfoJson;
    }

    public void setMarketinfoJson(String marketinfoJson) {
        this.marketinfoJson = marketinfoJson;
    }

    public String getExtParam() {
        return this.extParam;
    }

    public void setExtParam(String extParam) {
        this.extParam = extParam;
    }

    public Integer getSimilarUp() {
        return this.similarUp;
    }

    public void setSimilarUp(Integer similarUp) {
        this.similarUp = similarUp;
    }

    public Integer getSimilarDown() {
        return this.similarDown;
    }

    public void setSimilarDown(Integer similarDown) {
        this.similarDown = similarDown;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TSimilarklineStock (");

        sb.append(releaseTime);
        sb.append(", ").append(tradeDate);
        sb.append(", ").append(stockCode);
        sb.append(", ").append(stockName);
        sb.append(", ").append(marketCode);
        sb.append(", ").append(closelyStockCode);
        sb.append(", ").append(closelyStockName);
        sb.append(", ").append(klineStartDate);
        sb.append(", ").append(klineEndDate);
        sb.append(", ").append(similarRate);
        sb.append(", ").append(riseChance);
        sb.append(", ").append(marketinfoJson);
        sb.append(", ").append(extParam);
        sb.append(", ").append(similarUp);
        sb.append(", ").append(similarDown);

        sb.append(")");
        return sb.toString();
    }
}
