/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 股票市场信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TStockmarketInfo implements Serializable {

    private static final long serialVersionUID = 398325659;

    private Timestamp releaseTime;
    private Date      tradeDate;
    private String    ratioSh;
    private String    ratioSz;
    private String    ratioSy;
    private Integer   totalUp;
    private Integer   totalDown;
    private String    comment;
    private String    remark;

    public TStockmarketInfo() {}

    public TStockmarketInfo(TStockmarketInfo value) {
        this.releaseTime = value.releaseTime;
        this.tradeDate = value.tradeDate;
        this.ratioSh = value.ratioSh;
        this.ratioSz = value.ratioSz;
        this.ratioSy = value.ratioSy;
        this.totalUp = value.totalUp;
        this.totalDown = value.totalDown;
        this.comment = value.comment;
        this.remark = value.remark;
    }

    public TStockmarketInfo(
        Timestamp releaseTime,
        Date      tradeDate,
        String    ratioSh,
        String    ratioSz,
        String    ratioSy,
        Integer   totalUp,
        Integer   totalDown,
        String    comment,
        String    remark
    ) {
        this.releaseTime = releaseTime;
        this.tradeDate = tradeDate;
        this.ratioSh = ratioSh;
        this.ratioSz = ratioSz;
        this.ratioSy = ratioSy;
        this.totalUp = totalUp;
        this.totalDown = totalDown;
        this.comment = comment;
        this.remark = remark;
    }

    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    public Date getTradeDate() {
        return this.tradeDate;
    }

    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    public String getRatioSh() {
        return this.ratioSh;
    }

    public void setRatioSh(String ratioSh) {
        this.ratioSh = ratioSh;
    }

    public String getRatioSz() {
        return this.ratioSz;
    }

    public void setRatioSz(String ratioSz) {
        this.ratioSz = ratioSz;
    }

    public String getRatioSy() {
        return this.ratioSy;
    }

    public void setRatioSy(String ratioSy) {
        this.ratioSy = ratioSy;
    }

    public Integer getTotalUp() {
        return this.totalUp;
    }

    public void setTotalUp(Integer totalUp) {
        this.totalUp = totalUp;
    }

    public Integer getTotalDown() {
        return this.totalDown;
    }

    public void setTotalDown(Integer totalDown) {
        this.totalDown = totalDown;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TStockmarketInfo (");

        sb.append(releaseTime);
        sb.append(", ").append(tradeDate);
        sb.append(", ").append(ratioSh);
        sb.append(", ").append(ratioSz);
        sb.append(", ").append(ratioSy);
        sb.append(", ").append(totalUp);
        sb.append(", ").append(totalDown);
        sb.append(", ").append(comment);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
