/*
 * This file is generated by jOOQ.
*/
package test.boot.entry.mysql.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * topx股票信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTopxStockinfo implements Serializable {

    private static final long serialVersionUID = -1490253650;

    private Timestamp  releaseTime;
    private Short      type;
    private String     subType;
    private Date       tradeDate;
    private String     stockCode;
    private String     stockName;
    private BigDecimal stockPrice;
    private String     growthRate;
    private String     marketValue;
    private String     riseChance;
    private String     industry;
    private String     extParam;
    private String     trunoverRate;
    private String     growth;
    private String     avgRatio;
    private Integer    similarUp;
    private Integer    similarDown;
    private Timestamp  updateTime;

    public TTopxStockinfo() {}

    public TTopxStockinfo(TTopxStockinfo value) {
        this.releaseTime = value.releaseTime;
        this.type = value.type;
        this.subType = value.subType;
        this.tradeDate = value.tradeDate;
        this.stockCode = value.stockCode;
        this.stockName = value.stockName;
        this.stockPrice = value.stockPrice;
        this.growthRate = value.growthRate;
        this.marketValue = value.marketValue;
        this.riseChance = value.riseChance;
        this.industry = value.industry;
        this.extParam = value.extParam;
        this.trunoverRate = value.trunoverRate;
        this.growth = value.growth;
        this.avgRatio = value.avgRatio;
        this.similarUp = value.similarUp;
        this.similarDown = value.similarDown;
        this.updateTime = value.updateTime;
    }

    public TTopxStockinfo(
        Timestamp  releaseTime,
        Short      type,
        String     subType,
        Date       tradeDate,
        String     stockCode,
        String     stockName,
        BigDecimal stockPrice,
        String     growthRate,
        String     marketValue,
        String     riseChance,
        String     industry,
        String     extParam,
        String     trunoverRate,
        String     growth,
        String     avgRatio,
        Integer    similarUp,
        Integer    similarDown,
        Timestamp  updateTime
    ) {
        this.releaseTime = releaseTime;
        this.type = type;
        this.subType = subType;
        this.tradeDate = tradeDate;
        this.stockCode = stockCode;
        this.stockName = stockName;
        this.stockPrice = stockPrice;
        this.growthRate = growthRate;
        this.marketValue = marketValue;
        this.riseChance = riseChance;
        this.industry = industry;
        this.extParam = extParam;
        this.trunoverRate = trunoverRate;
        this.growth = growth;
        this.avgRatio = avgRatio;
        this.similarUp = similarUp;
        this.similarDown = similarDown;
        this.updateTime = updateTime;
    }

    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    public Short getType() {
        return this.type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public String getSubType() {
        return this.subType;
    }

    public void setSubType(String subType) {
        this.subType = subType;
    }

    public Date getTradeDate() {
        return this.tradeDate;
    }

    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    public String getStockCode() {
        return this.stockCode;
    }

    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    public String getStockName() {
        return this.stockName;
    }

    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    public BigDecimal getStockPrice() {
        return this.stockPrice;
    }

    public void setStockPrice(BigDecimal stockPrice) {
        this.stockPrice = stockPrice;
    }

    public String getGrowthRate() {
        return this.growthRate;
    }

    public void setGrowthRate(String growthRate) {
        this.growthRate = growthRate;
    }

    public String getMarketValue() {
        return this.marketValue;
    }

    public void setMarketValue(String marketValue) {
        this.marketValue = marketValue;
    }

    public String getRiseChance() {
        return this.riseChance;
    }

    public void setRiseChance(String riseChance) {
        this.riseChance = riseChance;
    }

    public String getIndustry() {
        return this.industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getExtParam() {
        return this.extParam;
    }

    public void setExtParam(String extParam) {
        this.extParam = extParam;
    }

    public String getTrunoverRate() {
        return this.trunoverRate;
    }

    public void setTrunoverRate(String trunoverRate) {
        this.trunoverRate = trunoverRate;
    }

    public String getGrowth() {
        return this.growth;
    }

    public void setGrowth(String growth) {
        this.growth = growth;
    }

    public String getAvgRatio() {
        return this.avgRatio;
    }

    public void setAvgRatio(String avgRatio) {
        this.avgRatio = avgRatio;
    }

    public Integer getSimilarUp() {
        return this.similarUp;
    }

    public void setSimilarUp(Integer similarUp) {
        this.similarUp = similarUp;
    }

    public Integer getSimilarDown() {
        return this.similarDown;
    }

    public void setSimilarDown(Integer similarDown) {
        this.similarDown = similarDown;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TTopxStockinfo (");

        sb.append(releaseTime);
        sb.append(", ").append(type);
        sb.append(", ").append(subType);
        sb.append(", ").append(tradeDate);
        sb.append(", ").append(stockCode);
        sb.append(", ").append(stockName);
        sb.append(", ").append(stockPrice);
        sb.append(", ").append(growthRate);
        sb.append(", ").append(marketValue);
        sb.append(", ").append(riseChance);
        sb.append(", ").append(industry);
        sb.append(", ").append(extParam);
        sb.append(", ").append(trunoverRate);
        sb.append(", ").append(growth);
        sb.append(", ").append(avgRatio);
        sb.append(", ").append(similarUp);
        sb.append(", ").append(similarDown);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
